version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    environment:
      DSN: ${DSN}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    network_mode: host
    volumes:
      - pytube_cache:/opt/app/pytube_cache
    command: ["python3", "main.py"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    environment:
      DSN: ${DSN}
    network_mode: host
    depends_on:
      - backend
    command: ["uvicorn", "asgi:app", "--host", "0.0.0.0", "--port", "${PORT}"]

volumes:
  pytube_cache:
