INSERT INTO "channel" ("id", "title", "added") VALUES
('UCDPnSqLmYqHadD6VkrRiarg', 'RizaNovaUZ', CURRENT_TIMESTAMP),
('UCPG6OP7eL7kLuyFpQMdqYSA', 'ВЛАДУС', CURRENT_TIMESTAMP),
('UCFBcrywVNeUOqtJgGhPEvQg', 'TheBrainDit', CURRENT_TIMESTAMP),
('UCkJpb5Ie9JAnWsASKDe_xpQ', 'Милана Хаметова', CURRENT_TIMESTAMP),
('UC0cWWruNMb95iCBEOzPnjRA', 'Компот', CURRENT_TIMESTAMP),
('UCDRVc_LN4TSbD86Rl18l9kQ', 'БЕРИ И ДЕЛАЙ', CURRENT_TIMESTAMP),
('UC5hNc6nMPLmcgygWgdHifgw', 'Ярик Кeнт', CURRENT_TIMESTAMP),
('UCOjjJFywLQTzZcARKsTUzXA', 'DaiFiveTop', CURRENT_TIMESTAMP),
('UCWXCAM8i0N6ZdShx8EqPSzg', 'БРУНО', CURRENT_TIMESTAMP),
('UC-Bc-4nV2-Tk4Af2rqrmrjA', 'HomeAnimations - Мультики про танки', CURRENT_TIMESTAMP),
('UCI-t7aBR9T38EzLaNNXLLqA', 'ЕвгенБро', CURRENT_TIMESTAMP),
('UCYFc8A8ZxeanxfBm4dyJUNg', 'KTV', CURRENT_TIMESTAMP),
('UCGTl_sQxago30b5vfoMomCg', 'Watch Me', CURRENT_TIMESTAMP),
('UCZUrS0zDszsXI_5ir_tI3cg', 'windy31', CURRENT_TIMESTAMP),
('UCWrmbQy_KxoBTAHCU7HiErg', 'ARGEN', CURRENT_TIMESTAMP),
('UCE76CBkDX591pxzps6bySOw', 'Super Polina', CURRENT_TIMESTAMP),
('UC-27_Szq7BtHDoC0R2U0zxA', 'AdamThomasMoran', CURRENT_TIMESTAMP),
('UCXTMoE1XgvxN4iCt5-gZzCw', 'Познаватель', CURRENT_TIMESTAMP),
('UCQXRhiyzUqZIz7-WJYJ7PaQ', 'Скорти', CURRENT_TIMESTAMP),
('UCC83eap-hc6uFQHRJ2F2LNg', 'TheKateClapp', CURRENT_TIMESTAMP),
('UC2tsySbe9TNrI-xh2lximHA', 'A4', CURRENT_TIMESTAMP),
('UCwQcna2wh3QtGx_VJVvzTyw', 'Доктор Гнус', CURRENT_TIMESTAMP),
('UCKj4BooYGVlBTXW21nOwcgQ', 'Alex Boyko', CURRENT_TIMESTAMP),
('UCoeD-36OhnnV6OPAfBBd7jQ', 'B0MBER SHOW', CURRENT_TIMESTAMP),
('UCu7TZ_ATWgjgD9IrNLdnYDA', 'Little Big', CURRENT_TIMESTAMP),
('UCGu-ydjHNguhpnPZXBFRBgw', 'DakPlay', CURRENT_TIMESTAMP),
('UCTzzh49iUjkikX6ni8uYbSA', 'ZAZABoo TV', CURRENT_TIMESTAMP),
('UCZEqXoz7G4sPniv_hJJbVhw', 'Ольга Матвей', CURRENT_TIMESTAMP),
('UCYtpIExuf1E6rpz84UjtQZQ', 'telblog.net', CURRENT_TIMESTAMP),
('UCpFJWSlmXbQVgti5s49PkSg', 'Robzi', CURRENT_TIMESTAMP),
('UCZYd-fQ0oSnldtcnxt94vMw', 'ХАБИБ', CURRENT_TIMESTAMP),
('UCf31Gf5nCU8J6eUlr7QSU0w', 'Marmok', CURRENT_TIMESTAMP),
('UCN0zdwk6Zi-Fxf75ERXDFCw', 'ЦИМУС', CURRENT_TIMESTAMP),
('UCCiGUQiWcz3lKev49TX8-Ew', 'FixEye', CURRENT_TIMESTAMP),
('UCvWxubhZYxVf_SVhXA-PHjA', 'ПАША МОРИС', CURRENT_TIMESTAMP),
('UCaj7AVYY8kNjmmNYWXg3YGg', 'Луана', CURRENT_TIMESTAMP),
('UCnbxcA3kZ_uUYIBHNvxpDQw', 'ДНЕВНИК ХАЧА', CURRENT_TIMESTAMP),
('UCthfjHehYgSyhf8ONjzJMUw', 'Gazgolder', CURRENT_TIMESTAMP),
('UCM44x9uWlx__9M9Y2IFhxzQ', 'HiMan', CURRENT_TIMESTAMP),
('UCJatXmy5PyaZ6gFs-NEAFWQ', 'Sasha Spilberg', CURRENT_TIMESTAMP),
('UC-qQJ-PiW3wfNhfxL0tQD9Q', 'Пятый канал Россия', CURRENT_TIMESTAMP),
('UCSmqZkD74x3TLt6eRM5GhTg', 'Даргас', CURRENT_TIMESTAMP),
('UC2Ru64PHqW4FxoP0xhQRvJg', 'ТОПЛЕС', CURRENT_TIMESTAMP),
('UCptqD42e_8DPpbgtaG-4sxg', 'Mr DeKart', CURRENT_TIMESTAMP),
('UCOug6HHVNWDpnU-m5kDNwvw', 'Mary Senn', CURRENT_TIMESTAMP),
('UCubxWD7pK_GkU9a3aaWmqdg', 'HOOOTDOGS', CURRENT_TIMESTAMP),
('UC5A-Wp9ujcr5g9sYagAafEA', 'TVSmeshariki', CURRENT_TIMESTAMP),
('UCUllb83Lugbka-rvF6Nutxg', 'KREOSAN', CURRENT_TIMESTAMP),
('UCPW5hBUmI-bsdWCMoD78tHw', 'Владимир Шмонденко', CURRENT_TIMESTAMP),
('UC7TkMpfCCRwhi8vbTCAOw-A', 'Quantum Games', CURRENT_TIMESTAMP),
('UChrF3GDVcuViElgQ7dQDb5A', 'ЛОКИ БОБО', CURRENT_TIMESTAMP),
('UCPOxKewOHmwumtiIfFyhFaw', 'My little Nastya', CURRENT_TIMESTAMP),
('UCdliAx3gHPrWju5VPetxWEw', 'Марк Бартон', CURRENT_TIMESTAMP),
('UCZQrA6Jnw08iF8GcFx4VDWg', 'Max TV', CURRENT_TIMESTAMP),
('UCXdLsO-b4Xjf0f9xtD_YHzg', 'ELLO', CURRENT_TIMESTAMP),
('UCJHLDABSk22tuRHH8KcwEZg', 'Funny Friends', CURRENT_TIMESTAMP),
('UC8j5GsMc0pjInklm4DfwCZQ', 'Джел', CURRENT_TIMESTAMP),
('UCTETCQ47GKVJR9drGMQFS1w', 'GHOST', CURRENT_TIMESTAMP),
('UCNnSNNsd9zCVERp1phyRcaw', 'Dr. Berg - официальный русскоязычный канал', CURRENT_TIMESTAMP),
('UCBByzLy3MGJT8UMVLYLScNg', 'Гараж 54', CURRENT_TIMESTAMP),
('UCQs_EpePwVeGqPT1sqTHz6w', 'Манкиту Сhannel', CURRENT_TIMESTAMP),
('UCCxjEtqox7wP7PPMX8rACdg', 'Flazin', CURRENT_TIMESTAMP),
('UCPWj5glOYDsZye7R0ZAgdyw', 'Ador Player', CURRENT_TIMESTAMP),
('UCbMa4OByYMCGeOgyLujB8iw', 'Дима Сивчик', CURRENT_TIMESTAMP),
('UCBP903se6pAfQrLT-akYCkA', 'РАЙЛЮХА', CURRENT_TIMESTAMP),
('UCsK9VJe_zGuHQ3X8zbOWdJg', 'Русский Мясник', CURRENT_TIMESTAMP),
('UCp07Dwx0hHg3tM1Is8kQy4Q', 'Filipin is bro', CURRENT_TIMESTAMP),
('UCENeeLCbbDNAP-664-t26FA', 'RusGameTactics', CURRENT_TIMESTAMP),
('UCj3ZYlmofqiDzt4w00KXljQ', 'Жизнь Виа', CURRENT_TIMESTAMP),
('UCaUYEpZMc9SLaqb5oLxGOFw', 'Super Max', CURRENT_TIMESTAMP),
('UCkEiEd4fV3pvUmcoJYacDqA', 'Эдисон Перец', CURRENT_TIMESTAMP),
('UCNVy3JfDYZ8jgsipemTMiGA', 'ZAKATOON', CURRENT_TIMESTAMP),
('UCQxV3HY_LXjjg3K_JiUvHBQ', 'Кушать Хочу', CURRENT_TIMESTAMP),
('UCIQ1PyEVzV2sc4CXHKH2cSg', 'Dobryak', CURRENT_TIMESTAMP),
('UCyN8Cpug_YwyAKCXbJ9jXrg', 'КиноМУР', CURRENT_TIMESTAMP),
('UC608azSGWiQYi5ImYgOZgdg', 'Epic Media', CURRENT_TIMESTAMP),
('UCD3cxCSDwsNVrOfHHpcqwQA', 'ПУШКА', CURRENT_TIMESTAMP),
('UCzKJ5CGa4PDB2UgUw0vKKYA', 'Dream Team House', CURRENT_TIMESTAMP),
('UCFTq_8SXc-SByisJqDZp9ZQ', 'ЮМОР ICTV - Официальный канал', CURRENT_TIMESTAMP),
('UCF0yfUFQlNS67JpGIh_9ApA', 'Паша Пэл', CURRENT_TIMESTAMP),
('UCRRXjDR3Fl_mQGuNw86w98A', 'Valera Ghosther', CURRENT_TIMESTAMP),
('UCX3-D0Ypw6-sqI8KXgXcp6Q', 'Настя ЧПЕК Туман', CURRENT_TIMESTAMP),
('UCh3yCLRgNaVrgSB6rCdQV_g', 'Калнина Наталья', CURRENT_TIMESTAMP),
('UCKZHn9_c685SxzLtsVI8eJQ', 'Владислав Шудейко', CURRENT_TIMESTAMP),
('UCQpx_LTX4Q34Fz76YDfGwgw', 'ЗОМБИ ЧЕЗ', CURRENT_TIMESTAMP),
('UCWKSMczTMjVjYmTMV4ZUZEQ', 'Коннор', CURRENT_TIMESTAMP),
('UCiPsX9jmY6Loe6F8EE6DPMQ', 'MY JOYS PINK', CURRENT_TIMESTAMP),
('UCQTzJnAqWZwzH0GCp1hIsFg', 'МЯТНЫЙ', CURRENT_TIMESTAMP),
('UCiE3TqG7v_bXZCYB_FaFvDw', 'Весёлый Кот', CURRENT_TIMESTAMP),
('UCjcjjOUxGWhGgrHM7kpTjyw', '제이제이 튜브 [JJ Tube]', CURRENT_TIMESTAMP),
('UCkrbi2bmw7DQuuC8k4TP-QA', 'TRUE GYM MMA', CURRENT_TIMESTAMP),
('UCQ2L7O1KDK7ze75dSe1C-yg', 'Nazzy', CURRENT_TIMESTAMP),
('UCqhw0vbc5tAmyQk656yP2kQ', 'PeReC - KLygeR', CURRENT_TIMESTAMP),
('UCqo61OZaNzi7XIiNMENhdmA', 'Стас Ёрник', CURRENT_TIMESTAMP),
('UCQYhXJ3rLz6YVtnC1f_CrHw', 'Куклы против нас', CURRENT_TIMESTAMP),
('UC5hcH25pD-rgIlQvzErgE7A', 'oblomoff', CURRENT_TIMESTAMP),
('UCkkTyNJPZ3tKbEVFY5IEOJg', 'Мирби', CURRENT_TIMESTAMP),
('UCgxTPTFbIbCWfTR9I2-5SeQ', 'Навальный LIVE', CURRENT_TIMESTAMP),
('UCIn-l6zKGAwpJ5NtZFgsVwg', 'BRAIN TIME', CURRENT_TIMESTAMP),
('UCocemgp-kMkgdECI1yAhbTA', 'It''s Experimentators', CURRENT_TIMESTAMP),
('UC32velEjgFxI08yXZOD22dg', 'Zёбра', CURRENT_TIMESTAMP),
('UCygfz98LH30AOeBEeh26xuA', 'MELOMAN VIDEO', CURRENT_TIMESTAMP),
('UCFM6I2EqybjKQ8osIxdn9Aw', 'MyPack', CURRENT_TIMESTAMP),
('UCzSGIHxvFPNyXb-o7juhGjA', 'StarPro', CURRENT_TIMESTAMP),
('UCRP4EhX1Op-jL7D87PB3qhQ', '808', CURRENT_TIMESTAMP),
('UCr36GmlGjNQ2RYWJXrbzvwQ', 'Просто Feliks-ks-ks', CURRENT_TIMESTAMP),
('UCSJZUvjFwid3SQ-E4kMB9hg', 'RYZE', CURRENT_TIMESTAMP),
('UCvfNirFbGeijfIWG88TMb_g', 'Demaster', CURRENT_TIMESTAMP),
('UCjkpITUKrPHdKa5Jkk7X8gw', 'Дизель Студио', CURRENT_TIMESTAMP),
('UCr4TOnBWci6RaNI87lf2sow', 'Alex Vikodinov', CURRENT_TIMESTAMP),
('UCsRbA_leAOKaeDLXmGEmHjg', 'Film', CURRENT_TIMESTAMP),
('UCjm6XUTNSz8Q68WqJIMJ0eQ', 'ABRACADABRA TV', CURRENT_TIMESTAMP),
('UCSz2-EHUfnKJk55e_xGIHHg', 'LavrenSem', CURRENT_TIMESTAMP),
('UCf8H1wdwb_3O5JRSPHoGbjQ', 'Yasemin Gotovit', CURRENT_TIMESTAMP),
('UCGyZblDN5afu78KyIJ0Ovbg', 'perpetuumworld', CURRENT_TIMESTAMP),
('UCzmO2w9-4d0-YyT_JlDDM1A', 'Deny Montana', CURRENT_TIMESTAMP),
('UCry39FTohgDCCSR9pVyFDzg', 'Merry Margo Live', CURRENT_TIMESTAMP),
('UCoSZkP0mVJd1S5GUGALzdnA', 'Central Partnership', CURRENT_TIMESTAMP),
('UC3VBuU-Ywv1qJGXLk05R-Dg', 'Monster School', CURRENT_TIMESTAMP),
('UCfHPrVIc0QavHNRvCwugWbQ', 'MnogoNotka. Com', CURRENT_TIMESTAMP),
('UC1EubwyksxHrpJZ9DvebeqQ', 'Dream Team Show', CURRENT_TIMESTAMP),
('UCEScTo5Hk1YXsCqGW1zgQEw', 'топКино', CURRENT_TIMESTAMP),
('UCa6jiW7904mUpUyPqAKRYiA', 'MELOMAN MUSIC', CURRENT_TIMESTAMP),
('UCTUjwDljDdBVAVpJ6H3B7zw', 'ГАБАР', CURRENT_TIMESTAMP),
('UCFvr5qtcq0xu_rwejp-ME8g', 'Manifest Сhannel', CURRENT_TIMESTAMP),
('UCaCyjTZo0yY2UoKxASfms9w', 'Галина Кухня', CURRENT_TIMESTAMP),
('UCmeLhJSpEdc4-4FuEKRkASQ', 'Рецепты Simple Food с Юлией Шевчук', CURRENT_TIMESTAMP),
('UCwpfuE8mL7oUy5_Nc1-9UFA', 'SANISHOW', CURRENT_TIMESTAMP),
('UCeVJc-SX_GJ54F_ZbOsTzGg', 'Dinara Salimova', CURRENT_TIMESTAMP),
('UCzM7YXiJk0zSLWAiT5JE0XA', 'BAD BARBIE', CURRENT_TIMESTAMP),
('UCGgjgLt5n8w6Zgmc-ceALlQ', 'Funny Anni', CURRENT_TIMESTAMP),
('UCmk6JWT6pf5FVsSH4jJ_2Bw', 'HUSMUT : ХАСМУТ / ХАСки и малаМУТ /', CURRENT_TIMESTAMP),
('UCpG4Cvq-Q4eN-3l_2er7QJg', 'Вся Правда', CURRENT_TIMESTAMP),
('UC0IAjf7iwTI2Iyk8jSXArjg', 'Канал Кейна', CURRENT_TIMESTAMP),
('UCJaCPPXppyU-v-T3DInLV5g', 'KINOFILM TV', CURRENT_TIMESTAMP),
('UCb2MY_nDHibmqaJgG2XDLZg', 'Hi idontfirst', CURRENT_TIMESTAMP),
('UC4WC9TkTTtnsVz6Ay1zE9KA', 'druemae', CURRENT_TIMESTAMP),
('UCApdP81v1rMFGiFUq-A7vBQ', 'Hajime', CURRENT_TIMESTAMP),
('UCVabytSq-Mewk0vxAHNznGg', 'Добрые советы', CURRENT_TIMESTAMP),
('UCOJf39BZ-T8DVRqflg5enGw', 'Коллекция Рецептов', CURRENT_TIMESTAMP),
('UCigoz5z4eB-yGZCZhzvdRFw', 'Magic Pets', CURRENT_TIMESTAMP),
('UCJxNqkbomzYhGxqhyQaED8g', 'Тохан', CURRENT_TIMESTAMP),
('UCUTeLM4oql94nuu6xd9hjiQ', 'АНЮТКА-МАЛЮТКА', CURRENT_TIMESTAMP),
('UC1Apwh59z8ff7ETT7aJNOxg', 'Корисне TV', CURRENT_TIMESTAMP),
('UCr7XrKHdxcPZ9afdqx38RoA', 'Muslima Soliha', CURRENT_TIMESTAMP),
('UCO4hWU1s0caDEscdVV0my-A', 'Юни', CURRENT_TIMESTAMP),
('UC5JLXMuSXsD1T7ZDoAeqJ-A', 'Вкусно Просто и Доступно', CURRENT_TIMESTAMP),
('UCq7JZ8ATgQWeu6sDM1czjhg', 'StopGame', CURRENT_TIMESTAMP),
('UCR2jSuaFk6Xocd--5SLoVow', 'Mak', CURRENT_TIMESTAMP),
('UCeXnZDZJW2AWOj1z_QOlz8w', 'Как МАМА', CURRENT_TIMESTAMP),
('UC9TL4XmmUXM3gx8fX7GtI-g', 'ISLAM. TV', CURRENT_TIMESTAMP),
('UC2Ztc82bXrd6XZgvtgkoCrw', 'Русское Кино', CURRENT_TIMESTAMP),
('UCT9uh07OtVk9heoKwDdqhHg', 'Дикий Лось', CURRENT_TIMESTAMP),
('UClbfI5NAOb9WoHhnsQe8ekQ', 'Mechanic', CURRENT_TIMESTAMP),
('UCMFyh6mw8lF6-ILZCT4zJ7w', 'EVA mash', CURRENT_TIMESTAMP),
('UCHS2LM1n3f5cyL-ebgkqyLw', 'Союзмультфильм', CURRENT_TIMESTAMP),
('UCP-kgqy07P9gc1owtXBmsqw', 'By Krash', CURRENT_TIMESTAMP),
('UCkZivHrFdFIljKFbAG_pNbQ', 'WTFакт', CURRENT_TIMESTAMP),
('UCr0bcOAnZR365lcm6h2vdbg', 'KiKiDo LIFE', CURRENT_TIMESTAMP),
('UCYfYQ1lmPwPdxjBpW_rMJ7w', 'RADIO TAPOK', CURRENT_TIMESTAMP),
('UC0vJpVswBWFOyDKQy5YhMjQ', 'Админ Пэнн', CURRENT_TIMESTAMP),
('UCn5X-Y80Vvk3rd9epecXhsA', 'comedoz', CURRENT_TIMESTAMP),
('UCRc21BeZykbSUHZDGRvi5zQ', 'Еда на любой вкус', CURRENT_TIMESTAMP),
('UC50_B4lI9UIlZBXWPaQ-vQA', 'Витя Перчик', CURRENT_TIMESTAMP),
('UC1CchA0SjApw4T-AYkN7ytg', 'IGM', CURRENT_TIMESTAMP),
('UCyGszKjNudY6hOhUlB9W8VQ', 'Sveta Sollar', CURRENT_TIMESTAMP),
('UCaY08MNW5C097-0je7xT6fA', 'Научпок', CURRENT_TIMESTAMP),
('UCIMXNTOhVpMn7XFxaN2P4JQ', 'ПОТУСТОРОННИЕ', CURRENT_TIMESTAMP),
('UCVeIDAXRgg_KPd2pV2deX-w', 'Skreeper', CURRENT_TIMESTAMP),
('UCWvFgYK5a0PGhYnRMXeQxlw', 'Кладовая Бэкста', CURRENT_TIMESTAMP),
('UCs4cGNX7xRaCmoBywFfjUUA', 'OfficialZelel', CURRENT_TIMESTAMP),
('UC9ejV2UE9AcLQTlaZSAmD9g', 'Neyrolix', CURRENT_TIMESTAMP),
('UCSKXRJ7PV5ApPwZkE_boIJA', 'РУСЛАНЧИК', CURRENT_TIMESTAMP),
('UCR_NE6tCWMDsMkw0mZZhW4g', 'ДАМБО MUSIC', CURRENT_TIMESTAMP),
('UCV1wBbcyzBoNmSXwYT3fWsg', 'Umeloe TV', CURRENT_TIMESTAMP),
('UCIaGsqHfeEAoV69Y0zc0XHg', 'Sasha Ice', CURRENT_TIMESTAMP),
('UCH5KHzRe9tpp-JyJ92C31og', 'llluiko', CURRENT_TIMESTAMP),
('UCRr9hxwMjZVApCxLZAxseXw', 'Erik Show', CURRENT_TIMESTAMP),
('UCZC7x1xvAQYvMQezKViOiCA', 'GoldenBurst', CURRENT_TIMESTAMP),
('UCDeDnXAb4qBjdHweGPJPriA', 'MisterKey', CURRENT_TIMESTAMP),
('UCHQ_lZkc7M8e7cdjmkATJXw', 'Мамины рецепты', CURRENT_TIMESTAMP),
('UCr1_S1awwC-GRsnHnr1-BCw', 'King Dm', CURRENT_TIMESTAMP),
('UChlsw028XAfDcqkli_8rrVg', 'Сакит Самедов', CURRENT_TIMESTAMP),
('UCrnVbCC1rv4IQroBwaCfImA', 'Арина Данилова', CURRENT_TIMESTAMP),
('UCW0vtJy0fmLBO8TNIOUAoDg', 'Кулинарим с Таней', CURRENT_TIMESTAMP),
('UCrdSQEkzjhy_czNcvJ1fmGw', 'Фани Хани', CURRENT_TIMESTAMP),
('UCDCe24N-VookTDNJ2miXmOQ', 'W_O_B_B_L_E_R', CURRENT_TIMESTAMP),
('UCvZFn7w2bEpNNt29GE5ppjg', 'Шарипов Руслан', CURRENT_TIMESTAMP),
('UC7a67UzUooER3YhkOBZl8nA', 'Слушай Quran', CURRENT_TIMESTAMP),
('UCMiPeXEaXBJBRkpNHJ4fZjQ', 'Solyarchin', CURRENT_TIMESTAMP),
('UCHDl4zUzU0VLFG036unHY-w', 'Black Beats', CURRENT_TIMESTAMP),
('UCzqkMWywUuUdFzxZkCBrZ7g', 'Вика Андриенко', CURRENT_TIMESTAMP),
('UCsaxk8Tn9rcUNhKhJwmbP0g', 'Posnavatel TV', CURRENT_TIMESTAMP),
('UCdy4E9igBBGLe-RMA0f9UVQ', 'VideoLand', CURRENT_TIMESTAMP),
('UCjbLX05VnkZAmnmNp-_CUkA', 'Здоровье и Долголетие', CURRENT_TIMESTAMP),
('UCP43oXul6ROrNfjOl8Ff4EQ', 'Hell Door', CURRENT_TIMESTAMP),
('UCOvgPCK0ZmKYwGGbdS49nKg', 'mc ARTUR', CURRENT_TIMESTAMP),
('UC-trfay77jr3XRgY9RHQ3hQ', 'ВИКТОРОВИЧ', CURRENT_TIMESTAMP),
('UCUBoIo2p7GSRMt1YcSswDEw', 'ЛЕВ ПРОТИВ', CURRENT_TIMESTAMP),
('UCuQsXgtPrppIkSE7GWjp7HA', 'JOHAN', CURRENT_TIMESTAMP),
('UC4rdGijkmGX-qo7tjstu-pA', 'NSK Show.', CURRENT_TIMESTAMP),
('UCzK8PeP5ERrHUvHQi1Pdr5A', 'ЯЯНА', CURRENT_TIMESTAMP),
('UCX7j9gyhEwbRCZogvit5R5Q', 'МАРМАЖ', CURRENT_TIMESTAMP),
('UCgtAOyEQdAyjvm9ATCi_Aig', 'AlexGyver', CURRENT_TIMESTAMP),
('UCn_igsnR6UkszaB6yFZSvPQ', 'Petr Savkin', CURRENT_TIMESTAMP),
('UClTIwWZu3b9CzgzLU5Tr9Ng', 'Yuliya Small', CURRENT_TIMESTAMP),
('UCen2uvzEw4pHrAYzDHoenDg', 'Тимур Сидельников', CURRENT_TIMESTAMP),
('UCpNzWUlO6PVb_v7chefBnig', 'GalileoRU', CURRENT_TIMESTAMP),
('UC5Raw-NuCoGFyuZHbA7Sy3g', 'Настя AmyMyr', CURRENT_TIMESTAMP),
('UCegbn_C_Eb-iKxN065xVlHg', 'ЧЁ КАВО', CURRENT_TIMESTAMP),
('UC3nMZLRNh-3dI9JAAkcikBA', 'MALFA', CURRENT_TIMESTAMP),
('UCOsKzQ4ldGoYTFTp7lo4Diw', 'AZAMM', CURRENT_TIMESTAMP),
('UC5Uy-OWRSWnl7zkqopQJqaQ', 'Procvetok', CURRENT_TIMESTAMP),
('UCbIxZ4MRRtYDHJ7gthi-ZYQ', 'Скретч', CURRENT_TIMESTAMP),
('UC1As3uk1ROhGfAhaT6B2_zA', 'Stuntexru', CURRENT_TIMESTAMP),
('UCGzfmBOI0dFy8CYV4szCkXA', 'COOL DAD на Русском', CURRENT_TIMESTAMP),
('UCw-NeLZsmZL1ZL04TMaPaHA', 'marazm', CURRENT_TIMESTAMP),
('UC-iU28QW_832Fx_3RJ_vYPQ', 'апвоут', CURRENT_TIMESTAMP),
('UClTYGNdQTwp2w3PhOpmVIkw', 'КОШКА ЛАНА', CURRENT_TIMESTAMP),
('UC3M_RxlDLqUPreOpa9git5A', 'Детектив Войд', CURRENT_TIMESTAMP),
('UCTsJtoNaZBYQhbIxS0-XEkQ', 'Master_Sergeich', CURRENT_TIMESTAMP),
('UCCnvz2rVBkQajGUiekDQ3Hg', 'Yuri The Professional', CURRENT_TIMESTAMP),
('UCXMTSawP2E1YcQGmMIw9WoQ', 'Стинт', CURRENT_TIMESTAMP),
('UCnnbdrQfCpSta_9LdP-HPwA', 'Elena Matveeva', CURRENT_TIMESTAMP),
('UCupPSveSIrZjQ1oZA29Q1JQ', 'Mr.Freeze ►', CURRENT_TIMESTAMP),
('UChfeK9NHpgHrO-4384Q9NjQ', 'KOSMO', CURRENT_TIMESTAMP),
('UCL5xTvMc3zmoTkcf5BEEK_w', 'WeiT Media', CURRENT_TIMESTAMP),
('UC3zqz87NP_nJsxAaQ_2D8eA', 'Black Horse', CURRENT_TIMESTAMP),
('UCtC45u3rZOYzCEcsNUs5CUg', 'Сырок', CURRENT_TIMESTAMP),
('UC_ape4qbV-kBBPERFsN9M1Q', 'Yan Dilan', CURRENT_TIMESTAMP),
('UCd6ojl6AkCtAprtEVD1E7qw', 'Julia Fun', CURRENT_TIMESTAMP),
('UCHgAHf2aRKGxllxFWSBWoqw', 'Вкусное дело', CURRENT_TIMESTAMP),
('UCc9UhR5B-LQzUst01nUnUYw', 'FOMENKOF Music', CURRENT_TIMESTAMP),
('UC86DMwzxzk1DWqnaAjibUHQ', 'Уральские Пельмени', CURRENT_TIMESTAMP),
('UCryDIgPuqQNt1cL5R3rp7iw', 'Pat04Chek', CURRENT_TIMESTAMP),
('UCsTGeNxaCVc2Boqw-SZVmwg', 'SHAMAN', CURRENT_TIMESTAMP),
('UC0zA5Bvv3lS2UBkLx6J6HpA', 'Нюся ТВ', CURRENT_TIMESTAMP),
('UCreZ0TYdHi-i7zhi97U5T1Q', 'Геннадий Горин', CURRENT_TIMESTAMP),
('UC5Ob2zi4pkJfra-kdcmG99w', 'Vashchenko Live', CURRENT_TIMESTAMP),
('UC75rw6sNo6duBTH_O-808PQ', 'Wika Toriia', CURRENT_TIMESTAMP),
('UC86GApUFFz8apkkT_ANZ3Cg', 'Sopha Kuper', CURRENT_TIMESTAMP),
('UCbS15KQNGgLdEeHHSUDJJcQ', 'Ярослав Сумишевский', CURRENT_TIMESTAMP),
('UCL2CdwOsPS-xkTuaOvHxrMQ', 'ВКУСНО и ПОЛЕЗНО', CURRENT_TIMESTAMP),
('UCmGjRgBGNWDWLStSHVUPO1Q', 'Viki Show PLAY', CURRENT_TIMESTAMP),
('UCo0gqwjsVtBtlj1jLZOnyHA', 'YOUNG', CURRENT_TIMESTAMP),
('UCRgbyMytcwJwT86rlbBHFzQ', 'START', CURRENT_TIMESTAMP),
('UCnuh-G_j8wMc5F4mEXDfpnQ', 'Даник Кек', CURRENT_TIMESTAMP),
('UCnXppDx0xzfKqOafJunzcEw', 'Искусство харизмы', CURRENT_TIMESTAMP),
('UCOaU9phwe8pr9FNrLpRHUcQ', 'Lil Boy', CURRENT_TIMESTAMP),
('UCPC6bMuLAJUrVJTvD3VZ3wQ', 'Выпечка и кулинария.', CURRENT_TIMESTAMP),
('UC2EWJZ5GxYPLzb_AOkirIOQ', 'Nikitos Show', CURRENT_TIMESTAMP),
('UCpWfV2axqyiRCZuk3cJXOAg', 'У Жоржа', CURRENT_TIMESTAMP),
('UCqbzgUspmnD40kwlY5rhgDQ', 'FitStars', CURRENT_TIMESTAMP),
('UCqTjE54bhQ0tvtxaHHHM-hA', 'Standoff 2', CURRENT_TIMESTAMP),
('UCIupfj3rki6dfjQqFKbXzMA', 'Cut The Crap', CURRENT_TIMESTAMP),
('UCnlsBWvqXj4jVgXYODOkWXQ', 'INSTARDING', CURRENT_TIMESTAMP),
('UC-rntvBxAngmY89sxOX-9TA', 'Hanna11-тиктокер с 4 мультами', CURRENT_TIMESTAMP),
('UCwd0QUcZSa5iGjt-v8z5w2g', 'Лиса Рулит', CURRENT_TIMESTAMP),
('UCSSxl15HbebvPp_fvBNr6Ww', 'Даша Боровик', CURRENT_TIMESTAMP),
('UCSU6G0iZ5MI7bIM8pTl_kaw', 'ПриветТачка', CURRENT_TIMESTAMP),
('UCSxXoOF9zs25Xw6BcewTQHw', 'TheRelizzz / STUDIO', CURRENT_TIMESTAMP),
('UCtGw6h7S9POPQbsI39jSspg', 'ZeeMan', CURRENT_TIMESTAMP),
('UCtL8BZsUg6iT-eQxv7nVApw', 'KOVALEVSKIY', CURRENT_TIMESTAMP),
('UCtqBQxhyU3610ZRYSibOhOw', 'ЮТУБЕР', CURRENT_TIMESTAMP),
('UCTsNlOo-TcXVs8I-pKOxb2A', 'ANDREY MARTYNENKO', CURRENT_TIMESTAMP),
('UCufdN4pY0MRAYvjUpJ9jsPw', 'Цветкова Наталья', CURRENT_TIMESTAMP),
('UCUFl0SxF14-eZGTxhWuhM8Q', 'Уголок Акра', CURRENT_TIMESTAMP),
('UCuil8trPUFgs2PzVAXoxOkw', 'Ислам Итляшев', CURRENT_TIMESTAMP),
('UCVPst_iSyaVYpuOP4ogRhlw', 'KunUZ', CURRENT_TIMESTAMP),
('UCVume2jn_1zO-INXVqCkGLQ', 'AXA GOTOVIT', CURRENT_TIMESTAMP),
('UCw7sVUMfBQp1ExHvyTcWctw', 'EvoNeon FIFA', CURRENT_TIMESTAMP),
('UC3BU_HMFitl_pvRgqd8slEw', 'polya_tut', CURRENT_TIMESTAMP),
('UCwLTi_1yOgDNf9i3bhBibCA', 'Дневник Депутата', CURRENT_TIMESTAMP),
('UCWShhk31e6HRMDfvOGPTXpw', 'Юмилия', CURRENT_TIMESTAMP),
('UCxNrQrlxfO-P2iTlwzea0LA', 'Глюк', CURRENT_TIMESTAMP),
('UCXoAjrdHFa2hEL3Ug8REC1w', 'DW на русском', CURRENT_TIMESTAMP),
('UCy1D4WGprdBxv0FaC6IH-wg', 'Лум Планет', CURRENT_TIMESTAMP),
('UCYCe8nGbLbMCzQ13lAvyQLg', 'Звездный Капитан', CURRENT_TIMESTAMP),
('UC_yoNMPdmbZFK-ctvNJ_2Kg', 'PanArmenian TV', CURRENT_TIMESTAMP),
('UCzXTNApTYz6Cwqh6Naadu1A', 'Россия23', CURRENT_TIMESTAMP),
('UC3wGCqoIZmnJI65NHEq1VGg', 'Юрий Андреевич Фролов', CURRENT_TIMESTAMP),
('UCejPi1LjTEK2kuZdAp-XWUQ', 'Акакий - МАЙНКРАФТ', CURRENT_TIMESTAMP),
('UC5ydvqLtSbBqbxuQJwaGvUA', 'Movie Hall', CURRENT_TIMESTAMP),
('UC6DkN5CmU7H5fx4yGRvAgqw', 'Риколит', CURRENT_TIMESTAMP),
('UC6r7WAQEBceDnEtSQi4MZtA', 'Корявый VLOG', CURRENT_TIMESTAMP),
('UCIWbvEaoTs8qtfVwi6BXkxQ', 'Sodyan', CURRENT_TIMESTAMP),
('UC7f5bVxWsm3jlZIPDzOMcAg', 'Хауди Хо™ - Просто о мире IT!', CURRENT_TIMESTAMP),
('UC8T9kBa--meNGWMgNzntwZA', 'Lina Win', CURRENT_TIMESTAMP),
('UC8TfnoSqHuzq9magOZClnLw', 'Hype House Rus', CURRENT_TIMESTAMP),
('UCcJ42urZmoOG3IV0Okd8haw', 'Готовим дома', CURRENT_TIMESTAMP),
('UCF3vpLThY0LnoS-vtn2iibg', 'Mosqvin', CURRENT_TIMESTAMP),
('UCfTMv6dKjbH9kKMwBWAbiAQ', 'Dunyo Yangiliklari', CURRENT_TIMESTAMP),
('UCGl0oOVqvSzelMpO1gG7xFw', 'Настя Луч', CURRENT_TIMESTAMP),
('UCH0rKjflgPZGTJ8rbizmAsw', 'JUSTFAN', CURRENT_TIMESTAMP),
('UCh7N4E9xz7_Age3rOXsK_xw', 'Viki Melano', CURRENT_TIMESTAMP),
('UCHtvgXPPVX5X5BXP8cu7riQ', 'Супер Сериал', CURRENT_TIMESTAMP),
('UCiE7Gx_LqbINklSQlmoJXSA', 'Дети и Родители', CURRENT_TIMESTAMP),
('UCJujNV3m9cOO8Yl9QjPqNcA', 'Говорит Макс Озвучка', CURRENT_TIMESTAMP),
('UCKF1jFt8PUs240B7ccRXDfw', 'CRYSTAL', CURRENT_TIMESTAMP),
('UCLF4cpVpZJF830G1tAsM_cA', 'Игрули TV', CURRENT_TIMESTAMP),
('UCLizDDpxiFRoqTLlMyGX7lQ', 'Joe Speen', CURRENT_TIMESTAMP),
('UCLjgT-_04v-bP-uJMOrYV_A', 'УМКА ШОУ', CURRENT_TIMESTAMP),
('UClUWvdPvq2Vj7MIkQ9XxVqA', 'Onliner', CURRENT_TIMESTAMP),
('UCMkBXn6Md4-d_raobglzoEw', 'VETREL', CURRENT_TIMESTAMP),
('UC_nk78JGygs4Tzk2nQOvWGw', 'ROMARIKI PLAY', CURRENT_TIMESTAMP),
('UCnLm2fpeBqs3alj_MSEl9WQ', 'Семейная кухня', CURRENT_TIMESTAMP),
('UC-nw1PHhZL0W21S8UN85b8w', 'ЗДОРОВОЕ ПИТАНИЕ', CURRENT_TIMESTAMP),
('UCObz_d8BslRLbGWnaRMv6Tg', 'ПАРАДОКС', CURRENT_TIMESTAMP),
('UComOP9kA1u4FtU9qlVMz-nA', 'ОНЛАЙН ФУТБОЛ', CURRENT_TIMESTAMP),
('UCoQvgO8xpuFV9fGLV1K_j1w', 'Sariq Bola TV', CURRENT_TIMESTAMP),
('UCor2cKyFti6ghDy6bH0-Mqw', 'Раш', CURRENT_TIMESTAMP),
('UCowcpOqZdHQqRujHie4MyRg', 'Фласка', CURRENT_TIMESTAMP),
('UCPeGsSJolGvikyKp7UBvjYQ', 'Татьяна Бугрий', CURRENT_TIMESTAMP),
('UCpTuLPXfIOcsPbvb2SIwD8w', 'ИМПРОКОМ', CURRENT_TIMESTAMP),
('UCuxytKkM5gbGja9gy1Hu9Bg', 'alaivine', CURRENT_TIMESTAMP),
('UCQ1NsRaJAq3wc0KIdRRs5MA', 'Marvel/DC: Geek Movies', CURRENT_TIMESTAMP),
('UCQdPrDypfQeY5euAPbdc11g', 'Физика от Побединского', CURRENT_TIMESTAMP),
('UCQvZD_M4nzOSyrPx0LfgOmQ', 'BBC News Uzbek', CURRENT_TIMESTAMP),
('UCrcweont1enc0tC0glD5l1w', 'Thebox - о технике и гаджетах', CURRENT_TIMESTAMP),
('UCR_X8eo8dqKNPZnyyAywXKw', 'PAZANDA ZAMIRA', CURRENT_TIMESTAMP),
('UCsh0-u4d_EpPQWvp6FkHonQ', 'TOPSY', CURRENT_TIMESTAMP),
('UCZVvxHrmbxsfkWm-g2Ol0eA', 'Victoria Portfolio', CURRENT_TIMESTAMP),
('UCj2QqbeCUZ82JMk492iGUQg', 'KINOKOS', CURRENT_TIMESTAMP),
('UCtFbE0nu4pYL8XTZOVC6X7A', 'Задор ТВ', CURRENT_TIMESTAMP),
('UCUtUdUaHk1Xfj_ZcZem_gaw', 'Зубарев', CURRENT_TIMESTAMP),
('UCv80wgA_QUvFijiTLJlJqeg', 'Sweet Home', CURRENT_TIMESTAMP),
('UCUzkpCMREk2AGgZwT55JizA', 'ВЛАДУС ИГРАЕТ', CURRENT_TIMESTAMP),
('UC3WmLKiZytzzIv1W9QweeEQ', 'OPTIMUS GANG', CURRENT_TIMESTAMP),
('UCvWyORw4cu6FdqCO9OM83xg', 'Омар в большом городе', CURRENT_TIMESTAMP),
('UCW4FEpd_Jai7N9xCHE2vbww', 'Alisa Che', CURRENT_TIMESTAMP),
('UCw4W8ZwRYYpP8Dul6Gsdgqg', 'Остроумно', CURRENT_TIMESTAMP),
('UCWcUsw5EBULSF4Eul0DLULg', 'Правое полушарие Интроверта', CURRENT_TIMESTAMP),
('UCWZRANKlxNe_4QKiqBBCTOQ', 'Антон Воротников', CURRENT_TIMESTAMP),
('UCxmldiymwJRSnLTijZO8MHw', 'Леха Медведь', CURRENT_TIMESTAMP),
('UCxZJzSkmD_B4S7pxDZ89qKQ', 'РОСТЯН', CURRENT_TIMESTAMP),
('UCY03gpyR__MuJtBpoSyIGnw', 'Droider', CURRENT_TIMESTAMP),
('UCyvSXfsFaBPZXEqEKoXLd2g', 'atv ihsan', CURRENT_TIMESTAMP),
('UCYZv9v_bwfMGc64gLRe34OA', 'SBS STORY', CURRENT_TIMESTAMP),
('UC7LOjGuvK6zZuJdAehFEubg', 'MASKIM', CURRENT_TIMESTAMP),
('UCzyodqoxqQlHj_KlMVEO62w', 'Риссман', CURRENT_TIMESTAMP),
('UC8KtLII_tbKTGt4pllHNeyA', 'Дастархан - вкусные рецепты', CURRENT_TIMESTAMP),
('UCIl8CkH5LUXqZ24ADJ419Wg', 'kinomiraru', CURRENT_TIMESTAMP),
('UCJqcrrl_xvb_xWrVisCYyAg', 'UNIVERSAL OSHXONA', CURRENT_TIMESTAMP),
('UCa6R89NcOsRJflRub4kUXqg', 'Sardor Rahimxon', CURRENT_TIMESTAMP),
('UCB3gRtX2gxkocgpWo5HvgOw', 'TURFA OLAM', CURRENT_TIMESTAMP),
('UCBQW75aPknKJTQ1-t-GA_mg', 'Anny May Day', CURRENT_TIMESTAMP),
('UCBxIz94B_duKCP1OMAD0aPg', 'Катя Медушкина', CURRENT_TIMESTAMP),
('UCcAQJDkK-Xf-YGCGAdAY3Ig', 'Дмитрий Бэйл', CURRENT_TIMESTAMP),
('UC_cNC-su5u92_ro-TUhn72g', 'ЭЙР', CURRENT_TIMESTAMP),
('UCcpNd-KO0b57e3sSr0ID0KQ', 'Лови Момент', CURRENT_TIMESTAMP),
('UCD9mU2rGEEwM9VDsvznPz5A', 'Tasty Food', CURRENT_TIMESTAMP),
('UCDalvE0aK5bHg7W4HVoXPRg', 'more tv', CURRENT_TIMESTAMP),
('UCeIUDBrc4AHM8W8NAPiWbZA', 'Ксения Куприкова', CURRENT_TIMESTAMP),
('UCEVywLKPJcyzqcWMswzooug', 'Алексей Земсков', CURRENT_TIMESTAMP),
('UCGZb9cGaTeHGXA2ti5PYKIQ', 'Кабан - Майнкрафт', CURRENT_TIMESTAMP),
('UCjxM3unn52MQw6tI7Kk7n_A', 'Я В ШОКЕ!', CURRENT_TIMESTAMP),
('UCL-nbxU92PJiCfCJLFMQ6OA', 'PilotZX6R', CURRENT_TIMESTAMP),
('UCmDPYQSxCVvMFOClPpVMgkg', 'Очкастый Красавчик', CURRENT_TIMESTAMP),
('UCnktTX3Ov3aFGRsiaoi8sMA', 'ТРЕНЕР', CURRENT_TIMESTAMP),
('UCNq9BbRHNP_ROZPOW_kJR1Q', 'Респект', CURRENT_TIMESTAMP),
('UCsTO-f7ij90TBSBxl7LbS7g', 'Gena Miller', CURRENT_TIMESTAMP),
('UCo3eXn385W3FqNnrlYfSe1A', 'SUPERTV', CURRENT_TIMESTAMP),
('UCo7EIWsPzZ-xZrj-17BTBig', 'Just Think', CURRENT_TIMESTAMP),
('UC0j_9poboewUN7WHoSFXQEw', 'Вивек Джоши', CURRENT_TIMESTAMP),
('UCOD61z-vlytlhJDKje5zNPw', 'americatvLETSPLAY', CURRENT_TIMESTAMP),
('UCqzgQIvvti_uZMoBxmxaihw', 'Михеев и Павлов', CURRENT_TIMESTAMP),
('UCjay7c-KSW2nC8Grq_q8tHg', 'Scammers', CURRENT_TIMESTAMP),
('UCsfwuKYRy5Pus4Tsx0fsAng', 'Дрымский', CURRENT_TIMESTAMP),
('UCsspPYzCpmjeStkAlcyK3yg', 'Always Alone', CURRENT_TIMESTAMP),
('UCSwZDdGEOY4lwk0rwDfoobQ', 'Товарищ Сафронов', CURRENT_TIMESTAMP),
('UC14mYP6eHJ2HlB0w3V4iEDw', 'SUBO', CURRENT_TIMESTAMP),
('UCTvLTz1K83pEOZucc04Hbwg', 'Velvet Music', CURRENT_TIMESTAMP),
('UCT_vpDYH-cszDn0SdoK2HTA', 'МЯТНАЯ ФАНТА', CURRENT_TIMESTAMP),
('UC22jUNo92LfZ46sqj2r25-w', 'Aleksia Official', CURRENT_TIMESTAMP),
('UCVfrS1hQiDwmZVY2GvNGbuw', 'PANDORA', CURRENT_TIMESTAMP),
('UCoHH5raTevyI35tfb1YF6qA', 'Илья Яшин', CURRENT_TIMESTAMP),
('UCV_uVHyjrmdGTOIJ1vCsG5w', 'Alina Charova', CURRENT_TIMESTAMP),
('UCwLMm2pP2TC8U9nAaYWHjFA', 'Sasha Chistova', CURRENT_TIMESTAMP),
('UCX0XSfrZbUa8xVzYHGn8Rtg', 'Хомки', CURRENT_TIMESTAMP),
('UCzTom8k7UduI9jcs6umWD9Q', 'Ольга Бузова', CURRENT_TIMESTAMP),
('UCnqF9YVsFsnP0UE3opZ8zgw', 'Vlad1000RR', CURRENT_TIMESTAMP),
('UC1jy2tjejSzSmsK_TLk-FhA', 'Muxakep Михакер', CURRENT_TIMESTAMP),
('UCrcBVWiA1QFy2qajUUE2MpQ', 'Самое Самое В Мире', CURRENT_TIMESTAMP),
('UCxn-8f1slSjWi_ABio5H8YA', 'JOHNNY И ЛУЧШИЕ БОИ WORLD OF TANKS!', CURRENT_TIMESTAMP),
('UCKU2qZWMWqrN9MiN1RDSKmQ', 'FNAF PLAY', CURRENT_TIMESTAMP),
('UCRQBxgGh4Rg3zduFEEd50nA', 'Грильков', CURRENT_TIMESTAMP),
('UCEMyt3qCrwa4wETvsheB95w', 'Саша Шапик', CURRENT_TIMESTAMP),
('UCx7Y6vzM8dTD-2VkP9M-DUQ', 'MC LAO', CURRENT_TIMESTAMP),
('UCHT4ZvUJJLOjMn7F6cZTGDQ', 'Slava Semeshko', CURRENT_TIMESTAMP),
('UCGZAjI7dDMwrtleThm-A_CA', 'Койот Питерсон', CURRENT_TIMESTAMP),
('UC1hs7BaV9bp245qnJ_GZnhA', 'Windy Beats', CURRENT_TIMESTAMP),
('UC5oZg3AX_dLTAJH-Y0TjZHQ', 'РанЗар - Рандомные Зарисовки', CURRENT_TIMESTAMP),
('UC63NFJiCmH7IbQKsZEmjBuw', 'FORUMHOUSE', CURRENT_TIMESTAMP),
('UC6OBB76NFySo4Wkdgu6gV9A', 'Линч', CURRENT_TIMESTAMP),
('UCagyhyIwIUoV7d57zzQLb9Q', 'Доф', CURRENT_TIMESTAMP),
('UCb64k6yqn3s4DlayVkbJ2qw', 'Обманутый Россиянин', CURRENT_TIMESTAMP),
('UCb9_Bhv37NXN1m8Bmrm9x9w', 'Игорь Негода', CURRENT_TIMESTAMP),
('UCbJ_jxOBRTz6MLE2b3EfyLQ', 'Xorazm NET', CURRENT_TIMESTAMP),
('UCBMcxvIVDkbNax7py7Tx1Mg', 'ZABENAFF team', CURRENT_TIMESTAMP),
('UCBQMUgjF4-ayrUpYdyYdxHg', 'Dizayn Jamoasi', CURRENT_TIMESTAMP),
('UCcHLJgRkV15QdjVaMPw16kQ', 'M E Д Ф И Л Ь М', CURRENT_TIMESTAMP),
('UCcIq2rEAjYxPZr2XNx4ECXw', 'Nastia Rizik', CURRENT_TIMESTAMP),
('UCcZF9AMIPrCFkLpu7_drQMg', 'OSHPAZ KELIN', CURRENT_TIMESTAMP),
('UCde09JOmT_obZ22lfQhgtkA', 'Marty Airsoft', CURRENT_TIMESTAMP),
('UCdYezGeRqqmiZKMVzopFJMA', 'ALI OSMANOV', CURRENT_TIMESTAMP),
('UC-em_HRcxwQcMhJUV9-3sbw', 'КОСТОЛОМ УЗБЕКИСТАН', CURRENT_TIMESTAMP),
('UCEzyqe39O5Q5RhtZQvGkq6A', 'АКАДЕМИЯ СМЕХА', CURRENT_TIMESTAMP),
('UCfaSK6K7hB3rAH7MLh8o6pw', 'Hubble', CURRENT_TIMESTAMP),
('UCfMB30UnkgmIyczPJgL88Mg', 'Удивительные Истории', CURRENT_TIMESTAMP),
('UCiM5hUA6JuAsSaVYZ5ShrVg', 'КамедиСтор', CURRENT_TIMESTAMP),
('UCK3AJaBVixx5BvCPLI2Ho9g', 'RWV Films', CURRENT_TIMESTAMP),
('UCL0tSwuCfEQi6EFSUJd83VQ', 'Andro-news.com', CURRENT_TIMESTAMP),
('UClMI18wDJR-myqBgtX6hVNQ', 'Привет, Бьянка!', CURRENT_TIMESTAMP),
('UClwiZO73C-j6m-XbeRmT2uQ', 'Зелена Планета', CURRENT_TIMESTAMP),
('UCmkJ3e4-X6Vd7UnTt8w96zQ', 'AliShoW', CURRENT_TIMESTAMP),
('UCnvziEmoKHOi4X9um0ydKBg', 'TheVovkaCom', CURRENT_TIMESTAMP),
('UCRW3VLiVep5Ud4Ovhj2eUyA', 'Мастерская Настроения', CURRENT_TIMESTAMP),
('UCEGfICV92gmM5w2t3gYfQDw', 'Magic Five', CURRENT_TIMESTAMP),
('UC4IPy7-vQCG2WAHn1qjZYvA', 'Симбочка Пимпочка', CURRENT_TIMESTAMP),
('UCw9L4gmA0nAsg6rlxBncByg', 'vanzai', CURRENT_TIMESTAMP),
('UC-b89a0Fw6pNoP-g-_qLeiw', 'sndk', CURRENT_TIMESTAMP),
('UCcGVrf54UcSyIFKlJic8T8A', 'Maryana Ro', CURRENT_TIMESTAMP),
('UCB4BRxXp2TsMCe8kU29h3Qw', 'Star Media', CURRENT_TIMESTAMP),
('UCkaUg9b9LplVoJdx1JwwyOg', 'NevoMusic', CURRENT_TIMESTAMP),
('UC2VQebBHZ0Jmh-AI2JrXkQg', 'OVER SHOW', CURRENT_TIMESTAMP),
('UCsIEFXNO4bxh0hW3-_z2-0g', 'Comedy Club', CURRENT_TIMESTAMP),
('UCrb7XNZEwPheovXjgbkH5vg', 'Телеканал СТБ', CURRENT_TIMESTAMP),
('UCaY1dtKcLMBzNTlCNcgeVfw', 'Найсик бро', CURRENT_TIMESTAMP),
('UCB99Xxp62Ptp6IRJSLVytAQ', 'clab_33', CURRENT_TIMESTAMP),
('UCwlB0jfzdLMQThC3cemfaFw', 'Masha Create', CURRENT_TIMESTAMP),
('UCTEZxfUxEtY4TOsFKv80fnQ', 'К-Media', CURRENT_TIMESTAMP),
('UCY9Nban7R4xGwR3sPJzfIqA', 'Top Five', CURRENT_TIMESTAMP),
('UCXUqOvkZol11UZt21vFsvQw', 'Max Maximov', CURRENT_TIMESTAMP),
('UC6Qkbg501AQodtwDGiEQR_Q', 'your fit', CURRENT_TIMESTAMP),
('UCvNUTTvGtULNzJIZXa1SyPg', 'Якушечкин Live', CURRENT_TIMESTAMP),
('UCQor-oqvVNR24ngy3y9U-ig', 'Andrey Burenok', CURRENT_TIMESTAMP),
('UC5T1H87BYG-tNzcMT6wUM6g', 'Футхакер', CURRENT_TIMESTAMP),
('UCQvAg5h4-xZeWkS4Y4ZlWzA', 'KINOFABRIKA', CURRENT_TIMESTAMP),
('UCdThPRpf84nKaHe-ETxTPhg', 'КОТЫ ЮТУБЕРЫ', CURRENT_TIMESTAMP),
('UCHVbYoo0wC9522QXOVAmKEQ', 'SIDELNIKOVVV', CURRENT_TIMESTAMP),
('UCarEmPSNN0TSQFSgTawOaMA', 'Милена Чижова', CURRENT_TIMESTAMP),
('UCYhXOzYd6-Vf4Uq-avzxh6g', 'ТУМКА', CURRENT_TIMESTAMP),
('UCTvXdgGkB4Ek864wuY-pYRg', 'Любовь Сазонова', CURRENT_TIMESTAMP),
('UCIx07h6JQsBGGZ3iyHqKgGA', 'Aleksandr Revva', CURRENT_TIMESTAMP),
('UCerK03vbFNIDc8ABS87gHzw', 'ЛЕСНЫЕ', CURRENT_TIMESTAMP),
('UCMR8RxR6J8U5QIJmUTADLAA', 'QWERTY', CURRENT_TIMESTAMP),
('UCkhZDx3AuNuMjxedmLxYhvg', 'nikushans', CURRENT_TIMESTAMP),
('UCWY_d_CEgiK_RfWFT_eA5-g', 'SJBody', CURRENT_TIMESTAMP),
('UCC354ogsLmMB4r2XFb_jhvQ', 'Alinka Malinka Tv', CURRENT_TIMESTAMP),
('UCCi9L_Rr4lql1l5O6eGHzOg', 'Совергон', CURRENT_TIMESTAMP),
('UCyB9SrEQ1KIo_lsivW2-Bjw', 'Готовим с Ириной Хлебниковой', CURRENT_TIMESTAMP),
('UCExKpE59YNNr3KZUm3xUQOQ', 'SHIRIN DUNYO', CURRENT_TIMESTAMP),
('UCfigubu63sDcQqwD0xRjsNg', 'Yuriy Tarabanov', CURRENT_TIMESTAMP),
('UCQUPfyCc45RG2OaVh6xjeJQ', 'Nafis Taomlar', CURRENT_TIMESTAMP),
('UC-3wrGRPLGVekt_M4ePbcsw', 'ЗАРАЗ', CURRENT_TIMESTAMP),
('UCu9Sf4ZtRAg20HRNMCj9NRg', 'Ляпота ТВ', CURRENT_TIMESTAMP),
('UCd_26xqPvQVhzsWMt6srgcQ', 'MrRissso', CURRENT_TIMESTAMP),
('UCBTkFkZUXfuPKisU6kZdn5A', 'Ozoda Official', CURRENT_TIMESTAMP),
('UCwAvzVA_F383Oko8RXnZ0bA', 'Насаат Медиа', CURRENT_TIMESTAMP),
('UCvwg7cgTwsNGIzhZntLFR1A', 'ФРАЙ', CURRENT_TIMESTAMP),
('UCsiMxHAf0sS4VzwOy9P0lvA', 'Kate Brush', CURRENT_TIMESTAMP),
('UCsJR1qQDNyFvsX_9_bNM63A', 'Доктор Дью', CURRENT_TIMESTAMP),
('UCsqvKSUCfliOIG4QMjdg8pA', 'Имморталиус', CURRENT_TIMESTAMP),
('UCs_xNajKMU60fbeIhcxStoA', 'Azattyk', CURRENT_TIMESTAMP),
('UCT5yaMwzQ_VQwP0ZIbTRuDg', 'бодя', CURRENT_TIMESTAMP),
('UCtkGIcCp__7XGcSlzEOkbuA', 'ВЛАДИМИР ДРЕВС', CURRENT_TIMESTAMP),
('UCU_yU4xGT9hrVFo6euH8LLw', 'SlivkiShow', CURRENT_TIMESTAMP),
('UCIjfTmz5uNAwZwkVX6Wjw3Q', 'TicTac', CURRENT_TIMESTAMP),
('UCCB4-saKfwGbUFO2-rRdUqQ', 'Lady Diana', CURRENT_TIMESTAMP),
('UCA8x119TMd1esbI3woeIbQg', 'Трум Трум СЕЛЕКТ', CURRENT_TIMESTAMP),
('UCGbwlbRGgOZQwGiDr-cxEzQ', 'LINE', CURRENT_TIMESTAMP),
('UCve3T2JUto59BcaBujrn-Lw', 'CheAnD ► Play', CURRENT_TIMESTAMP),
('UCbh7BxJWCMnWLwJ-traa6Wg', 'DAVA', CURRENT_TIMESTAMP),
('UCBqUi9mvN_jex4hlpgDP4Ow', 'Елена Райтман', CURRENT_TIMESTAMP),
('UCP0d9Chu2KSWNO74UBl1t1g', 'КОТЁНОК ЛАЙК', CURRENT_TIMESTAMP),
('UCqPSpViOkFJPodlL7wV8WNA', 'Бискас', CURRENT_TIMESTAMP),
('UCZH4Vx5QPuHnmGC7ANv0BdA', 'slavikmust [СлавикМаст]', CURRENT_TIMESTAMP),
('UCtnDD2vM8S4FcznwWjKDnig', 'АУКЦИОН КОНТЕЙНЕРОВ В США', CURRENT_TIMESTAMP),
('UC2kYzKESojoSZj0a-hB5sng', 'А ну-ка Давай-ка', CURRENT_TIMESTAMP),
('UCdySspSHtlMprXVzdjaG9uw', 'Ярик Лапа', CURRENT_TIMESTAMP),
('UC7VUPJfRyt57XoI7fBz1s1Q', 'Gufee.medalin', CURRENT_TIMESTAMP),
('UCx5Ss5P2GQ-q1Q62wXqf59A', 'Katya Klon', CURRENT_TIMESTAMP),
('UCJm9mc6RBNUkHy429BK9pUg', 'Anastasiz', CURRENT_TIMESTAMP),
('UCGSDJpG1YyXuOZ5lnt68LiA', 'БЕРИ И ДЕЛАЙ – Дети', CURRENT_TIMESTAMP),
('UC9diVCDUnRAB3buT1vLn4-w', 'FROST', CURRENT_TIMESTAMP),
('UCsIoBmCIpp62ikGuXA_4SoQ', 'Алиса МИМИ ЛИССА', CURRENT_TIMESTAMP),
('UCI4pqNOmYdAhWA4eqPjHWRw', 'Мы семья - We are Family', CURRENT_TIMESTAMP),
('UCvJiuCwOUfb7z-stNsDy0JQ', 'Cegou', CURRENT_TIMESTAMP),
('UCG4yz4wtp2E5S62L06yqC9w', 'ИЛЬДАР АВТО-ПОДБОР', CURRENT_TIMESTAMP),
('UCdfXOIogbMA7h7iBp--nmYg', 'DANIEL BOY', CURRENT_TIMESTAMP),
('UCHl0OvS2BxzVbIBiegeATyg', 'Mama I''m A Criminal', CURRENT_TIMESTAMP),
('UC6S1hSjVMFbB9WKv-qZKwuw', 'Юлик', CURRENT_TIMESTAMP),
('UClmI-b4_ro8UJLaNbiS9Isw', 'В Рейтинге', CURRENT_TIMESTAMP),
('UCAvrIl6ltV8MdJo3mV4Nl4Q', 'MrLololoshka (Роман Фильченков)', CURRENT_TIMESTAMP),
('UC_JnY_MRGd7idxBpXUSpLTw', 'Морковь PRO', CURRENT_TIMESTAMP),
('UCqtzZMiZ5Bng7HCxI6154gg', 'Макс Ващенко', CURRENT_TIMESTAMP),
('UCMCgOm8GZkHp8zJ6l7_hIuA', 'вДудь', CURRENT_TIMESTAMP),
('UC-Osiqly2kWjXcB6ElD2iCQ', 'Дима Гордей', CURRENT_TIMESTAMP),
('UCmyE72X4HsC7XD-z6QIQpzw', 'доктор Евдокименко', CURRENT_TIMESTAMP),
('UCNqktdxgAADBj36dC7VGOgg', 'LABELCOM', CURRENT_TIMESTAMP),
('UCrd7UM5OBtB0n1zl41qwCUw', 'EugeneSagaz', CURRENT_TIMESTAMP),
('UCM6hH7Xa0oanOQeh5RxeRAQ', 'Holdik', CURRENT_TIMESTAMP),
('UCO_j_ZAZzcoS5vDleoNbROQ', 'Anastasia Kosh', CURRENT_TIMESTAMP),
('UCM0lWLQuQhEKwq0qhdWejQA', 'Lesha Maisak', CURRENT_TIMESTAMP),
('UCUTYX1IOaUXqYB1_Ca5iXPQ', 'Декстер', CURRENT_TIMESTAMP),
('UCwZ6TJuh2PsR83k5PkkQx4A', 'LudaEasyCook Позитивная Кухня', CURRENT_TIMESTAMP),
('UCtsOtsolypZyB3pyg6Gluvw', 'MixShow', CURRENT_TIMESTAMP),
('UCtWY35eYO7jI9LnCRJxBGRQ', 'Bulkin', CURRENT_TIMESTAMP),
('UCTcnAmNuA2WTySV9VCQfWiw', 'Канал Яла', CURRENT_TIMESTAMP),
('UCv2hYhRYO8Fmbs5mUemz2oQ', 'smotraTV', CURRENT_TIMESTAMP),
('UCtGJ_XI0ZGwEmKZaj3VQITw', 'НАСТЯ ИВЛЕЕВА', CURRENT_TIMESTAMP),
('UCNb2BkmQu3IfQVcaPExHkvQ', 'SOBOLEV', CURRENT_TIMESTAMP),
('UCs_uv3QyUIQjBoL1Ij5BdlQ', 'Фиксики', CURRENT_TIMESTAMP),
('UCPT9_sNLoBLjH1uea7zpVIA', 'This is Хорошо', CURRENT_TIMESTAMP),
('UCtKnY1vJ37v-KPgejc2kkBQ', 'Найкращі серіали Ever', CURRENT_TIMESTAMP),
('UCtsY8R5ukYI8yTjV6ZKYOkg', 'ТИНТОК', CURRENT_TIMESTAMP),
('UCTtAl6SKR_Krv-vdy7o_ejA', 'Вкуснейшн с Lana ilanavi', CURRENT_TIMESTAMP),
('UCTw-VCsIbDE1V7lGyt4-m3w', 'HammAli & Navai', CURRENT_TIMESTAMP),
('UC9OT9jOB0BvaydyIEsqlRNw', 'Myron Iron', CURRENT_TIMESTAMP),
('UCRkQ5F-b2qU2rYE7-GfGkOA', 'Виталий Оpехов', CURRENT_TIMESTAMP),
('UC5c2noTCCJn_zJDwkvBs6jA', 'Fast Sergey', CURRENT_TIMESTAMP),
('UCrovV-U03gP-Prkn6HGRIjg', 'Топовский', CURRENT_TIMESTAMP),
('UCU8bQExxd38i-mnn-GLOtfA', 'UFC Russia', CURRENT_TIMESTAMP),
('UCjFPu8rOAk1hleLQH6-7_Hg', 'Edward Bil', CURRENT_TIMESTAMP),
('UCiUz8kxpIG1Zb4IoOUcudGQ', 'Miller Eva', CURRENT_TIMESTAMP),
('UCu6-zNydTcNRtnuIhGdFb4g', 'Садовый Мир', CURRENT_TIMESTAMP),
('UCqzhvLeBcNEJHq9dZDEit8Q', 'Веля', CURRENT_TIMESTAMP),
('UCwipTluVS2mjuhPtx2WU7eQ', 'Дима Масленников', CURRENT_TIMESTAMP),
('UCdD5Z5yfiGNMij-qMweAZkA', 'nnotochka', CURRENT_TIMESTAMP),
('UCWI7puXzGTPuxsoW2HD3XxQ', 'Boys and Toys', CURRENT_TIMESTAMP),
('UCdKuE7a2QZeHPhDntXVZ91w', 'Kuplinov ► Play', CURRENT_TIMESTAMP),
('UCHcvtngSbrakQiNLAKXiX_w', 'MAD SCIENCE', CURRENT_TIMESTAMP),
('UCl0lW3ojU3ERRNwu3fSIiUQ', 'Кинокомпания «Русское»', CURRENT_TIMESTAMP),
('UCa85JIfBxZgcrsd8Ar7Z9nw', 'Телеканал ICTV', CURRENT_TIMESTAMP),
('UC9XJvt8OT-9_8QHDBdqocaw', 'Жекич Дубровский', CURRENT_TIMESTAMP),
('UCHEE87fd9NhSiTI-ZAwlsrw', 'DIPT', CURRENT_TIMESTAMP),
('UCVnah-S-sByndtg9cHBxlOA', 'Мир Танков. Официальный видеоканал', CURRENT_TIMESTAMP),
('UCUGfDbfRIx51kJGGHIFo8Rw', 'Максим Кац', CURRENT_TIMESTAMP),
('UCp2J7GRxQ36QLqW4ReLLt5g', 'А поговорить?', CURRENT_TIMESTAMP),
('UCJsOVd61dzow401WI1hR-kg', 'Алексей Столяров', CURRENT_TIMESTAMP),
('UCxm5_Y8j9Bn7LxrSHMMJ0Pw', 'Аришнев', CURRENT_TIMESTAMP),
('UCy6p8krDY33mDRMt19YrlXg', 'ЛИТВИН', CURRENT_TIMESTAMP),
('UCBIfuwYslGljdRGWSELdaUw', 'Милс PLAY', CURRENT_TIMESTAMP),
('UCcsOhBOv3H7t28_1ah3DDCg', 'Smart Pizza', CURRENT_TIMESTAMP),
('UCZWkcTIGDg5gHyafm2M4Pig', 'UzbekFilmsHD', CURRENT_TIMESTAMP),
('UCdubelOloxR3wzwJG9x8YqQ', 'Телеканал Дождь', CURRENT_TIMESTAMP),
('UCuyhhCyM1ZWa1KUQYu3_Exg', 'Никита Берг', CURRENT_TIMESTAMP),
('UCWUi0SCvgAGNJyS3Jmfibow', 'Body Mania', CURRENT_TIMESTAMP),
('UCvcY2Bxk6_DU0WfwwCROBsQ', 'Пиксель', CURRENT_TIMESTAMP),
('UCUhtv0VMCbe3RVNr6Qz0lWQ', 'Доктор Комаровский', CURRENT_TIMESTAMP),
('UCiG0W88vIiJUPQdGIjqysMA', 'КАЛЯКА-МАЛЯКА', CURRENT_TIMESTAMP),
('UCKC0KDcTiwYVS2y_dN5fGlg', 'BUBBLEGUN', CURRENT_TIMESTAMP),
('UCNfxB3nWgDIpkItC6KSqKsw', 'Ridddle UA', CURRENT_TIMESTAMP),
('UCSYOvRiB12CnApfSC_GeFXg', '• Gerand •', CURRENT_TIMESTAMP),
('UCSunKgDsNIYsooxVG7sLWjQ', 'SHAMPANOV', CURRENT_TIMESTAMP),
('UCiVZttFkdEwMi3QXpRqFTzQ', 'Советское телевидение. ГОСТЕЛЕРАДИОФОНД', CURRENT_TIMESTAMP),
('UCUXqcY7bSoBOm2Ymx3QKpMQ', 'INSTASAMKA', CURRENT_TIMESTAMP),
('UCaJOGSrZtnTh-2WZcWFzufQ', 'TumkaGames / Тумка :3', CURRENT_TIMESTAMP),
('UCsnKU1R3r5PdtEbzYwspa5g', 'ДОКТОР ИСЧАНОВ', CURRENT_TIMESTAMP),
('UCdlfo5folV5oO5WsPgSE_Cw', 'Afinka', CURRENT_TIMESTAMP),
('UCa4grme_V_sz4c2P5B-hAIw', 'FILM.UA Group', CURRENT_TIMESTAMP),
('UCidEZ1TfAikhpKwh5xcqujQ', 'Я Кеша', CURRENT_TIMESTAMP),
('UC_Q1vhf7wcR_zGlc5ahAg0A', 'Игромания', CURRENT_TIMESTAMP),
('UCWiR9Ki8oDHZKt3TgfhJ-pw', 'Скай Топ', CURRENT_TIMESTAMP),
('UCfkBQO9E5JHBL5NAlIDXiag', 'Family Box VLOG', CURRENT_TIMESTAMP),
('UCEr3iPX6mtFSwc5U7iruo0w', 'Mehrob Music', CURRENT_TIMESTAMP),
('UC-LXU4tsyjbz5eHGedtF7gA', 'Elli Di Pets', CURRENT_TIMESTAMP),
('UCf9iZMkNmNJ8n0qw8mPbNGg', 'Александра Киевская', CURRENT_TIMESTAMP),
('UCjvuO1gMPI-7PB_eSXdtfmA', 'serial', CURRENT_TIMESTAMP),
('UCDx2-SCLzDaC4vlh2PCGYQA', 'Jove', CURRENT_TIMESTAMP),
('UCYXvAOKehklq8lXX9oJhsEg', 'MrUnfiny', CURRENT_TIMESTAMP),
('UCX3UhUaD2FSnFfxHqswRTuA', 'КОБЯКОВ', CURRENT_TIMESTAMP),
('UCTA4HigzJIbpU3iVP0-DPSg', 'Екатерина Ковалева', CURRENT_TIMESTAMP),
('UCkNoJaaAYclU54cs5ARnC6A', 'MrShadyMan', CURRENT_TIMESTAMP),
('UCZXO02K1uTTfZV1yLhtZs7A', 'Darti - Minecraft', CURRENT_TIMESTAMP),
('UCY0C6A3t3RTUN3BB65rWAgQ', 'Ленинград', CURRENT_TIMESTAMP),
('UCGrzKEXqpIX-SCStZs77o-A', 'karrambaby', CURRENT_TIMESTAMP),
('UCHPbrkmgqJpoKaGxrUmbMvA', 'Фильмы и Сериалы Студии Квартал 95', CURRENT_TIMESTAMP),
('UC4d3PcFfHvddK-6JRra7s_w', 'Котайн', CURRENT_TIMESTAMP),
('UCvosGl7ZQXmeSw2fxwUMOpQ', 'Bubenitta', CURRENT_TIMESTAMP),
('UCHrYTzwmDvMpsVXHkNjBQmA', 'Хижина Музыканта', CURRENT_TIMESTAMP),
('UCpbgBi44JsOwluXPHzegIcg', 'Маша Маева', CURRENT_TIMESTAMP),
('UCwPzq5yQwczLmivBX8zq7Mw', 'The Люди', CURRENT_TIMESTAMP),
('UCW0-JsQvk2drCyC_gt3Pipg', 'Лисса', CURRENT_TIMESTAMP),
('UCiUiZUDSpuiMiiecRBEOZEQ', 'Сериалы. Фильмы. Шоу', CURRENT_TIMESTAMP),
('UCXHczq_8PytR6mEJeUTTrqw', 'ViteC ► Play', CURRENT_TIMESTAMP),
('UCLNrn6a4Co8D6H7jRZtNPcA', 'X2DED', CURRENT_TIMESTAMP),
('UCOJRJqAaearydfTvGKriCPQ', 'German El Classico — АМКАЛ', CURRENT_TIMESTAMP),
('UCey3Heg5VxerB51ifaArDYQ', 'Фактория', CURRENT_TIMESTAMP),
('UCXFxgPppcehs2LoiKhkakQg', 'SuperCrastan', CURRENT_TIMESTAMP),
('UC7DFMwmTVwwSO2E5vs2GgQw', 'Игорь Войтенко', CURRENT_TIMESTAMP),
('UCnm_vYgguleXm0FL4F2vejg', 'Viki Show', CURRENT_TIMESTAMP),
('UC0qfFtXolx1UrElt2kd1niA', 'Вадим Бабешкин', CURRENT_TIMESTAMP),
('UC1-CSlW88o-ge88ELumtuHg', 'ZVUKM TV', CURRENT_TIMESTAMP),
('UCoMKxdrf8_pmg3X-_iDeNgQ', 'Готовим с Оксаной Пашко', CURRENT_TIMESTAMP),
('UCyjJpmRA7SbCPYDMNEOs1vg', 'Красавица и Чудовище ОФИЦИАЛЬНЫЙ КАНАЛ', CURRENT_TIMESTAMP),
('UCXDdPCUl4SKQlp0XdltIDgg', 'Alina FooDee', CURRENT_TIMESTAMP),
('UCCkG_UbtkgyIM38u_9SwdbA', 'NaStik', CURRENT_TIMESTAMP),
('UCVx86lX2cYywHGasLH9R1QQ', 'Мили Ванили', CURRENT_TIMESTAMP),
('UCVqJYFWsnkLEUkmmS-avyQg', 'Теперь я Знаю', CURRENT_TIMESTAMP),
('UCr5o-O2LPyxVb08MDjI53-Q', 'GERASEV', CURRENT_TIMESTAMP),
('UCBpKZtuLooxjSmYr_e6QBFA', 'MILANA STAR', CURRENT_TIMESTAMP),
('UCBnKMiYzbE9opd0Mtg9B7Dg', '55x55', CURRENT_TIMESTAMP),
('UCR-Hcwi27-Ee6VnGzmxE1pA', 'Данила Поперечный', CURRENT_TIMESTAMP),
('UCgQ1CeGtjCbkvslmG3zTAFA', 'ILYA STREKAL', CURRENT_TIMESTAMP),
('UCOcVByxOk_O7VbgM2ZAqkTQ', 'Скрынник Дмитрий', CURRENT_TIMESTAMP),
('UCT49EulAy9P2X6zgjOP7pSA', 'Привет, Я Ника!', CURRENT_TIMESTAMP),
('UCRxH-Wdf4c_2nDu3_lIQrvg', 'IVLEV CHEF', CURRENT_TIMESTAMP),
('UCoz6QG1iK_ji5-E_zoFODkg', 'CheAnD TV - Андрей Чехменок', CURRENT_TIMESTAMP),
('UCvQXaJTjA3jRucTKN4CGiwg', 'Осторожно: Собчак', CURRENT_TIMESTAMP),
('UCWb8EvFsUy9LV_TXPq1REBg', 'WorldBegemotKot † Страшные истории †', CURRENT_TIMESTAMP),
('UCWcriEtaV0tf1rp0-8HGmTA', 'Tez Kabar', CURRENT_TIMESTAMP),
('UC057NSSVc2663UcpoZ0C6EQ', 'Садхгуру — официальный канал на русском', CURRENT_TIMESTAMP),
('UCo_l_x30EbXrBoyjhCt14Kw', 'DOCTOR UZ', CURRENT_TIMESTAMP),
('UCtn_uu182ItXMmT3WFckJhQ', 'PLAYBOYZ TV', CURRENT_TIMESTAMP),
('UCIZh1qgtqweKcakAOHNvHyw', 'GAZ', CURRENT_TIMESTAMP),
('UCFWQBVsdq763yRDqO31NvbA', 'Ксения Левчик', CURRENT_TIMESTAMP),
('UCO3ZWDxdTeXPVSP1WTijl1w', 'ВЛАДУС — Майнкрафт', CURRENT_TIMESTAMP),
('UCBfJ30FMjlKHVjZf4WcJMxA', 'Егор Шип', CURRENT_TIMESTAMP),
('UC7JDoslazqzqa6xeu5C-7yA', 'Ловкий Слайм Сэм', CURRENT_TIMESTAMP),
('UCwAWqzhIYFKFtgU3dhtXEZg', 'Вкусная минутка', CURRENT_TIMESTAMP),
('UCFk9x8sAhxg5Ykb11Pf5g0g', 'PROSHKA', CURRENT_TIMESTAMP),
('UCAe4XfXD-WqP5FsGSO_h-xg', 'Джентльмены Синдиката', CURRENT_TIMESTAMP),
('UC76hYQ-bNPcNBybsbpCb4hw', 'dikiy_vadik', CURRENT_TIMESTAMP),
('UC8R1ldt81E86OgS7AMeGluA', 'САД, ОГОРОД,СВОИМИ РУКАМИ', CURRENT_TIMESTAMP),
('UC7ZoTgXWonv3Q0WWm5c00Pw', 'Ember West', CURRENT_TIMESTAMP),
('UCgRZN07WAh6E6Ib-zAcTExA', 'Max Deep', CURRENT_TIMESTAMP),
('UC9Zxu2GxtUFWcdhC3MI3HIw', 'Человеческий организм', CURRENT_TIMESTAMP),
('UC84J-P1AEat5jPz7C1vKhsw', 'Харчевников', CURRENT_TIMESTAMP),
('UCcCoFzc8L__zlGg8IUd-G0Q', 'Zhen Gongfu', CURRENT_TIMESTAMP),
('UCHy99JhFdqQhEzy2FU7FJ2w', 'Аниматор Лойсик', CURRENT_TIMESTAMP),
('UCkeS4qlso8xGwLKX5Vn9EBw', 'Видео Лепка', CURRENT_TIMESTAMP),
('UCbt1nwQXG6PZIn8iEgvMyVw', 'КиноМурка', CURRENT_TIMESTAMP),
('UC7F98YYhXCW8tDQFo9owCXQ', 'NILETTO', CURRENT_TIMESTAMP),
('UCxOJ083McFNRqUty-bgTx8Q', 'TaGs Play Theme', CURRENT_TIMESTAMP),
('UCGFN4z6_1R4KLnk3yvagUZQ', 'АВАНТЮРИСТ', CURRENT_TIMESTAMP),
('UCHRWh66zFu6-SxsQq2Mv-_g', 'Edik FunTube', CURRENT_TIMESTAMP),
('UCRFMpg5Q3Fko_Wdxh08yZ_g', 'Denis МЕХАНИК', CURRENT_TIMESTAMP),
('UCMZKCZ23VTy_D743H56iuJw', '123 GO! Russian', CURRENT_TIMESTAMP),
('UC6uVHEgl379D_2a1kq0s6Kw', 'World Street Fight Championship', CURRENT_TIMESTAMP),
('UCUJkV75hkQRa7ttz6Ks_Tsg', 'ACTION PAPA SHOW', CURRENT_TIMESTAMP),
('UCc-w5-p_9jQIN-ZIf-CHbRA', 'kotiynet', CURRENT_TIMESTAMP),
('UCUe5pwmem1_vOL6KvwiI6xQ', 'Dачник', CURRENT_TIMESTAMP),
('UCh-SRBZwSNnJaxB7QcxB2Zw', 'Вика Старикова', CURRENT_TIMESTAMP),
('UCvsV75oPdrYFH7fj-6Mk2wg', 'RC Buyer/ RC обзоры', CURRENT_TIMESTAMP),
('UCWd_ibVjSFOkm25PK27LDsQ', 'Группа Dabro / Дабро', CURRENT_TIMESTAMP),
('UCRQsPzh6NU4pk2KvebBahtw', 'SOLO', CURRENT_TIMESTAMP),
('UC8W2ELB-mC5s7z4vOEpPiTw', 'SUPER KELINCHAK', CURRENT_TIMESTAMP),
('UC6JSor-voKXNrZDYGyDpenw', 'Robo Top', CURRENT_TIMESTAMP),
('UC4VsltrCzcP-cTknlbU_9Lg', 'Топовый Пинск', CURRENT_TIMESTAMP),
('UCP9vBIdSfZR97nASaWMQkxg', 'КОТ ЛЕОНАРД', CURRENT_TIMESTAMP),
('UCPWvxc8QuP6gKYqrDdwaNJw', 'Феникс Кино', CURRENT_TIMESTAMP),
('UCOR-iqlcedb8VMnax37m3MQ', 'Eiro Nareth', CURRENT_TIMESTAMP),
('UCvPvF5tDp6rmeGTPtdpL74Q', 'Алексей Маматов | Клуб Активного Долголетия', CURRENT_TIMESTAMP),
('UCt3h-Y9FO9-21KD6g3x24XA', 'Тамир Шейх', CURRENT_TIMESTAMP),
('UCksJki6V80sbW87zu2A5zyA', 'СПЕЦЗАКАЗ', CURRENT_TIMESTAMP),
('UCJBiljvGiWjJDvetZ3QZnqA', 'cool.baybay', CURRENT_TIMESTAMP),
('UCeNyUl9q5i56rB2b2clxAhg', 'crazy russian experiments', CURRENT_TIMESTAMP),
('UCUE84Cta6VxXZ7bBnbeK2OA', 'Марина Жукова', CURRENT_TIMESTAMP),
('UCzOSNu12lCuRBdnpHyhLEgw', 'Дмитрий Дрожжин', CURRENT_TIMESTAMP),
('UC_wfQp3EVnGNee-GwGzKcSQ', 'ГАВЕР', CURRENT_TIMESTAMP),
('UCFzJjgVicCtFxJ5B0P_ei8A', 'Euronews по-русски', CURRENT_TIMESTAMP),
('UCep2ymw-rGbM7MqGCq8_g8g', 'Крипекс', CURRENT_TIMESTAMP),
('UCbDMaUm8uT2NNMfgHUf0M-w', 'TeM4iK', CURRENT_TIMESTAMP),
('UCVfQ8FrpFRLVtmPNbPoSPPA', 'Ekaterina Saibel', CURRENT_TIMESTAMP),
('UCeUGVe4-DQi1BEqdCGMJPnQ', 'Просто Путин', CURRENT_TIMESTAMP),
('UC48dBGzxjnenwKabSK_WOLQ', 'Тайна Жрицы', CURRENT_TIMESTAMP),
('UC750ojNf94wjQoCKd8A1OSA', 'Эзотерика для тебя * Магия * Советы * Ритуалы', CURRENT_TIMESTAMP),
('UCbSb8vETHKWUVqNaJ4kAdPQ', 'Глеб', CURRENT_TIMESTAMP),
('UCduvxcmOQFwTewukh9DUpvQ', 'Зоомагазин Четыре Лапы', CURRENT_TIMESTAMP),
('UCbPaiwu_qEC6XT2NrwjU08g', 'Хит-Шансон', CURRENT_TIMESTAMP),
('UC320CI8C_tgDdzgxFiUBEOQ', 'САНЯ ЧУМАКOВ', CURRENT_TIMESTAMP),
('UCBHwWYrgvBfJi8Je5zNGJJQ', 'Vitalik Ignatyuk', CURRENT_TIMESTAMP),
('UCIEKNcaDFTuI6lHpj-8LqYA', 'AlexBoy', CURRENT_TIMESTAMP),
('UC0RoWfEY2x5wmFASOk-wODQ', 'Хаски Бандит', CURRENT_TIMESTAMP),
('UC35OyVD-LCPDC8tRHoN1Sbg', 'Фильмы и Сериалы Дизель Студио', CURRENT_TIMESTAMP),
('UCHbUc28rq1oghUtrpTh-XGA', 'Princess', CURRENT_TIMESTAMP),
('UC5lUZ5FZlvU38zx9RcbAyRA', 'Поделкин', CURRENT_TIMESTAMP),
('UC5lvZc3icRkOcE9u7j_G-fA', 'Vredina Life', CURRENT_TIMESTAMP),
('UC4yHMRbOxXJA6DfqXk0Y4Aw', 'Крупнокалиберный Переполох', CURRENT_TIMESTAMP),
('UC6BdJHY0Vku9YQLDaoH0R1w', 'Елена Юлкина', CURRENT_TIMESTAMP),
('UC6Ib-bYadfXiNyGFbLlHaqQ', 'Кирилл Дикусар', CURRENT_TIMESTAMP),
('UC6pfIqKRA17eVset7Owj63A', 'Антон Алексеев', CURRENT_TIMESTAMP),
('UCbb-qqGdlVS7laUbUOTOXhg', 'Зона Лазерсона', CURRENT_TIMESTAMP),
('UC7jL8M3KBSO47ke9l1os_Fg', 'Red Cat', CURRENT_TIMESTAMP),
('UC8I2yszp8JtlvNhd4H6JblA', 'FrostDog', CURRENT_TIMESTAMP),
('UC8oyGrNFM1tHLux1gyDw9zg', 'Найс', CURRENT_TIMESTAMP),
('UC9BGxwtlIgZBimMgvc7TlXA', 'Viliriti', CURRENT_TIMESTAMP),
('UC9ql--q_LV7zhDI1CCO9Xdg', '1337LikeR', CURRENT_TIMESTAMP),
('UCeIL5_nLXHcPPba0MYhOJyg', 'Космические Шары', CURRENT_TIMESTAMP),
('UCaqfIFqJzo2j9AfIoKBWtDw', 'ЛаЛиЛу', CURRENT_TIMESTAMP),
('UCGL4OvhZ9-Nowr9U5UBS3yg', 'Иван Курапов', CURRENT_TIMESTAMP),
('UCbGLw6GoDQ7ujZnu-5Zfydw', 'Zhekastoporom', CURRENT_TIMESTAMP),
('UC6pyjZgCOlkxV62juSj9Ryg', 'POLI', CURRENT_TIMESTAMP),
('UCiwIy5q59aD-Nph5f-Zvp2A', 'БесогонTV', CURRENT_TIMESTAMP),
('UCc9pY6nxrdpYntXzQwOIqOw', 'Video Star', CURRENT_TIMESTAMP),
('UCceWYhe4JBjuRAVUMebsa1Q', 'Weebaby', CURRENT_TIMESTAMP),
('UCCH01_yMExcviH5PpO0coHg', 'LEGACY MUSIC', CURRENT_TIMESTAMP),
('UCcIZ_-tW8NTYkuxXuM5uXXw', 'Видео блог Доктора Шишонина', CURRENT_TIMESTAMP),
('UCCROBQj3rdGNc-E_aMpbV_A', 'MyGap', CURRENT_TIMESTAMP),
('UCcUVVGYn4SAP2zWh8L1_HHA', 'Funny Games TV', CURRENT_TIMESTAMP),
('UCd2HjPTV3Ict_WPITpB06KQ', 'Склад Корявого', CURRENT_TIMESTAMP),
('UCDF_NIAEkcAUvzxe1DUzaQA', 'Rozetked', CURRENT_TIMESTAMP),
('UCdvelJCElBAEFYjh8fjuCDw', 'Про здоровье', CURRENT_TIMESTAMP),
('UCeA20izeAJCJFrb-TdByF2Q', 'Dimas.tv', CURRENT_TIMESTAMP),
('UCE_BVgYgMY4w6PVyzrYWLsQ', 'The NeptooN', CURRENT_TIMESTAMP),
('UC-EnprmCZ3OXyAoG7vjVNCA', 'Stanford', CURRENT_TIMESTAMP),
('UCEnZxcVvM0mD6TDDwg_sbFg', 'Виталий Островский', CURRENT_TIMESTAMP),
('UCfLGEDbyezC3Bx9D0TmvcKw', 'Взрыв Мозга', CURRENT_TIMESTAMP),
('UCF-swD64kLu40As8yNjr81Q', 'Заброшенная Россия', CURRENT_TIMESTAMP),
('UCg54RsNxhg8KDO1yaNdQ45w', 'WATER', CURRENT_TIMESTAMP),
('UCg8ov7wuSEhzHBVpTgVaqYw', 'ОСОЗНАНИЕ', CURRENT_TIMESTAMP),
('UCh2ku44ACi1h6TlGNF6RKvA', 'Акыркы Кабарлар - Санжар Калматай', CURRENT_TIMESTAMP),
('UCh9SK585ydcuwNQzLSv73xg', 'Garena Free Fire CIS', CURRENT_TIMESTAMP),
('UCHL3OD9-Ze1WvihAapnd8sg', 'DISSA', CURRENT_TIMESTAMP),
('UCI54Kk8gfwZoQ8bzj7iZnWQ', 'Кинокомедии', CURRENT_TIMESTAMP),
('UCiglVNXBgjgzRniFCdWFVJA', 'Первый Хоррор Канал', CURRENT_TIMESTAMP),
('UCiJ6RBthQvEPI4UsSNtM8jw', 'Azattyq TV - Азаттық - Азаттык', CURRENT_TIMESTAMP),
('UCItUy5dUN24_1I8c6chpG7g', 'Gradus TV', CURRENT_TIMESTAMP),
('UCiWA1Ct_IdiUA8a-DTwBj9A', 'Во саду ли в огороде', CURRENT_TIMESTAMP),
('UCWtnmUD1X9DAI5qukMcYzeQ', 'Алена Митрофанова', CURRENT_TIMESTAMP),
('UCX2-frpuBe3e99K7lDQxT7Q', 'RC Buyer TV', CURRENT_TIMESTAMP),
('UC2eH4vw5JuVpzLDrCkxW2pQ', 'МУЗ-ТВ', CURRENT_TIMESTAMP),
('UC0bwuabO4JHHa-BMs00pHnQ', 'Alexander Kondrashov', CURRENT_TIMESTAMP),
('UC_3oKG5Szq-m6Xz-MjRZgpw', 'АНГЛИЙСКИЙ ЯЗЫК ПО ПЛЕЙЛИСТАМ', CURRENT_TIMESTAMP),
('UC101o-vQ2iOj9vr00JUlyKw', 'varlamov', CURRENT_TIMESTAMP),
('UCLJw4V0jXTr3UvGFhBQSE7Q', 'ПАРАДИГМА', CURRENT_TIMESTAMP),
('UC42SIHeNRlQLtGKS7YSL1tw', 'ARTEM WOLF', CURRENT_TIMESTAMP),
('UC3N4p9X5DjPCH184X-izRwA', 'Watch Movies - библиотека фильмов', CURRENT_TIMESTAMP),
('UC3cJiUuZlpF-pkzqvSskTpg', 'Stand-Up Club #1', CURRENT_TIMESTAMP),
('UC2bhfksrCXjguRr10mpkvag', 'СЛОВО ПАЦАНА', CURRENT_TIMESTAMP),
('UC-4AhkhvJeLmSXiEtAvPMfQ', 'AndroHack', CURRENT_TIMESTAMP),
('UC1eFXmJNkjITxPFWTy6RsWg', 'Редакция', CURRENT_TIMESTAMP),
('UC0nynvECv6feAPIEH3efZcQ', 'Kent.apk', CURRENT_TIMESTAMP),
('UCjMPa4FiyN82F4vkMGlFGrA', 'Веселые Игрушки', CURRENT_TIMESTAMP),
('UCLGnG6SffG60QKqw-PuCjng', 'Азамат Мусагалиев', CURRENT_TIMESTAMP),
('UCncVaU-OckSKV0tXt43HZfA', 'ПАПА И ДОЧКИ Games', CURRENT_TIMESTAMP),
('UC1_FrNtrgzFPQVHuwAAR3xQ', 'Hardcore Fighting Championship', CURRENT_TIMESTAMP),
('UC2lgvkAKm3jCSY4QB5JkNtg', 'Жак Фреско и Проект Венера', CURRENT_TIMESTAMP),
('UC3PNW3_vmoG6E-37_MDeBMg', 'Magic Family', CURRENT_TIMESTAMP),
('UCJUveMwaOQdmBlephJ5jASw', 'ARTUR MUSIC', CURRENT_TIMESTAMP),
('UCL6yyycvM81609YfYEf6x6g', 'Нурминский', CURRENT_TIMESTAMP),
('UC20n6cvq4SwlFtSpwzPa4XQ', 'Телеканал ЧЕ!', CURRENT_TIMESTAMP),
('UCLTgbvgydbIU3OQ0Z-PpTpA', 'Саша Квашеная', CURRENT_TIMESTAMP),
('UCM7-8EfoIv0T9cCI4FhHbKQ', 'Алексей Шевцов', CURRENT_TIMESTAMP),
('UCMbeqb9ZhsBUlwEdNXXEjZw', 'albert_cancook', CURRENT_TIMESTAMP),
('UCmk4zr_j-vXRba57P8TxKRA', 'Василиса Даванкова', CURRENT_TIMESTAMP),
('UCMpoPt5DaBcscn1eLQxLCwA', 'Тучный Жаб', CURRENT_TIMESTAMP),
('UCmWgyp0M9TputbssrNvUifQ', 'MysteryForce', CURRENT_TIMESTAMP),
('UC3HJv6JriejmABDHWi9OCjA', 'Milliy TV', CURRENT_TIMESTAMP),
('UC7mFtKMM819ZeYiwgbUyy0g', 'Мастерская Синдиката', CURRENT_TIMESTAMP),
('UCXJrRIC2ZkE0ieprot_wvyA', 'Кулинарный Микс с Кристиной Оловянниковой', CURRENT_TIMESTAMP),
('UC4yk2IPkgtRK63lUrWwr89A', 'Matt The Cat', CURRENT_TIMESTAMP),
('UC5cmCSWFykv--zAfb6S_uWw', 'Fancy smth.', CURRENT_TIMESTAMP),
('UC7Elc-kLydl-NAV4g204pDQ', 'Популярная политика', CURRENT_TIMESTAMP),
('UC647stBCZxmi6ua_4mZxr7g', 'Sevimli TV', CURRENT_TIMESTAMP),
('UC7qnYpVcuFbURi3E2E6_f6Q', 'Радіо Свобода', CURRENT_TIMESTAMP),
('UC8kI2B-UUv7A5u3AOUnHNMQ', 'Александр Невзоров', CURRENT_TIMESTAMP),
('UC9oLBiosH8I3muPxumGEVIg', 'Кузьма', CURRENT_TIMESTAMP),
('UC9OpmkDt-iR0sNAL29_zPJw', 'YangiKulgu Official', CURRENT_TIMESTAMP),
('UC9D_41XZiozyLLeRKVQIBmQ', 'Авторадио', CURRENT_TIMESTAMP),
('UCaNuwim22HctBJdJjEU7hJg', 'Мисс Николь', CURRENT_TIMESTAMP),
('UCAeCwHL4T91FKoYiFXHy0-g', 'TOP DOG', CURRENT_TIMESTAMP),
('UC6t2pfao0fh4zAr4tuIJzrA', 'МАША БЕЗ МЕДВЕДЯ', CURRENT_TIMESTAMP),
('UC5aNdQmTYqlSxJHS9Ld0pBw', 'AkStar', CURRENT_TIMESTAMP),
('UC81IJnCIsc7c0Bc4VKfx6IQ', 'Liza Nice', CURRENT_TIMESTAMP),
('UC6ZQezbR7LwGgxTB-xt0xAw', 'Шок', CURRENT_TIMESTAMP),
('UCAHCkDpk5bjGEfsmiRIDEqA', 'Ерокс', CURRENT_TIMESTAMP),
('UC8k2L8NWKFOk6eFMUUpoCEw', 'doctorpetrik', CURRENT_TIMESTAMP),
('UCxSXK-MJkaGsNhCv0YuccTg', 'Иван Эфиров', CURRENT_TIMESTAMP),
('UC5lt6mntn4AoCJ4g4Mbps9g', 'Amelka Karamelka', CURRENT_TIMESTAMP),
('UCBu3eTzufhcBLMhlJAmqDyg', 'Fantom', CURRENT_TIMESTAMP),
('UCCcprrrcbdaj14kYPjcbj9w', 'В гостях у Гордона', CURRENT_TIMESTAMP),
('UCClgnrIfArlWVWvaPc7KF7w', 'Асафьев. Жизнь', CURRENT_TIMESTAMP),
('UCcY245vE_FtqanRpMViOeSQ', 'СЕНЯ В ДЕЛЕ', CURRENT_TIMESTAMP),
('UCBQNrxUDpUWm7obRUs-FqYw', 'Ишутин богат душой', CURRENT_TIMESTAMP),
('UCBELlne6XFSBbYaSTDbCvvA', 'Galich Ida', CURRENT_TIMESTAMP),
('UCdb_kR-eluM3kScsoYRar5Q', 'Виктор Блуд', CURRENT_TIMESTAMP),
('UCBss5McqBPfUKk5OZES0WFA', 'Qewbite', CURRENT_TIMESTAMP),
('UCBG57608Hukev3d0d-gvLhQ', 'Настоящее Время', CURRENT_TIMESTAMP),
('UCbBSHw85WBOptJJLfEcH98Q', 'Valensia Lucky', CURRENT_TIMESTAMP),
('UCC8cx8WRapge_9KyfcbTWwg', 'Крамола', CURRENT_TIMESTAMP),
('UCY6zVRa3Km52bsBmpyQnk6A', 'Vert Dider', CURRENT_TIMESTAMP),
('UCCqQM_sRaeRyGdfL2fo6iPg', 'Maria OMG', CURRENT_TIMESTAMP),
('UCD3JX5aiXiFQeg0PwiMyI-Q', 'slow slow cow', CURRENT_TIMESTAMP),
('UCcBbiCpR-eBwL5l6H63lgfg', 'Skyeng: онлайн-школа английского языка', CURRENT_TIMESTAMP),
('UCCA2N6IgL1YtFEElvRmu5TQ', 'Fan Entertainment', CURRENT_TIMESTAMP),
('UCcEwV3KQEdSnolCQYX0JXSw', 'HOOPS', CURRENT_TIMESTAMP),
('UCBZNnwQOBirwpeWncqTj_KQ', 'Три Кота', CURRENT_TIMESTAMP),
('UCc2UzuPHYQytHnsZXo0xkVQ', 'GoB Channel', CURRENT_TIMESTAMP),
('UCfHd8ZyQK-5mG5k9XFmIaoA', 'Super.kg', CURRENT_TIMESTAMP),
('UCdu1AosJcTPsQYFolNHki8Q', 'SNAILKICK', CURRENT_TIMESTAMP),
('UCfJ0lFBtEKmIK47L7Hew0RA', 'ВУХУУ! ВАУ', CURRENT_TIMESTAMP),
('UCekJYjb2Eqkj7dSmpGl9KUA', 'Классные Мультики', CURRENT_TIMESTAMP),
('UCeKCxQDv6lWDSzuqUXGtMRA', 'МИНАЕВ LIVE', CURRENT_TIMESTAMP),
('UCFSPubeTn39vnhlFHWa1RJA', 'Chokirya', CURRENT_TIMESTAMP),
('UCF55G2O1iG85wk_TewFrM-Q', 'RussianMusicStars', CURRENT_TIMESTAMP),
('UCEN5iM5rjQtl-YsR_evcrXA', 'АлоЯ Вера', CURRENT_TIMESTAMP),
('UCE5dBnwxi9DS7-Ff_VEnITA', 'Big Russian Boss Show', CURRENT_TIMESTAMP),
('UCe2HVgifMO2KeCIqI0NqfOw', 'Одноклассники Forever', CURRENT_TIMESTAMP),
('UCg0Y6Q0m3A_5X0CPY-IG3Yg', 'Психолог Вероника Степанова', CURRENT_TIMESTAMP),
('UCgvwq97x__1U3C_4eutbr0w', 'BROS SHOW', CURRENT_TIMESTAMP),
('UCFvYljGofVfAm83Ixr6C5eQ', 'Mister Booble', CURRENT_TIMESTAMP),
('UCeNpzcxM-hUhnabwC7oZeYw', 'Трансформатор', CURRENT_TIMESTAMP),
('UCEVNTzTFSGkZGTjVE9ipXpg', 'AcademeG DailyStream', CURRENT_TIMESTAMP),
('UCGIj-5Yy5hhs8tAbE-hbCIQ', 'BRIGMAN', CURRENT_TIMESTAMP),
('UCFyeniESLZ9Ajb1HeXC3rnA', '1.1TV', CURRENT_TIMESTAMP),
('UCFxcToYcNu7ZGgegVfttjEQ', 'Райм', CURRENT_TIMESTAMP),
('UCgeval0um2gyuRhP1qch8Uw', 'Шеф-повар Василий Емельяненко', CURRENT_TIMESTAMP),
('UCyTDJHSzuKZ2JZO41c5Do1A', 'Ozodivideo', CURRENT_TIMESTAMP),
('UCYV8EwdZIIBagEZD11QtPwQ', 'Soderling', CURRENT_TIMESTAMP),
('UCyjf5CxCNEc9ALYlalBiKDQ', 'GEO', CURRENT_TIMESTAMP),
('UChsZtadN_SZixZ7P7gfE7Lg', 'Гитара с нуля- уроки игры на гитаре', CURRENT_TIMESTAMP),
('UC_Ij3QxHsTeeEdNv4_N7scA', 'Даша Дашевская', CURRENT_TIMESTAMP),
('UCJYT1-amSktM8j7QR1x3lAg', 'Dariya Rain', CURRENT_TIMESTAMP),
('UCif9J_f4J3TTvGvCDD3eXSA', 'Рики', CURRENT_TIMESTAMP),
('UCJDBeG3tqcHBNKH6yBLCRcQ', 'Angela Pearl', CURRENT_TIMESTAMP),
('UCK0iilUPnz6LXDF6EJpzGbA', 'Супер Стас', CURRENT_TIMESTAMP),
('UCKoFMFiKx297VCuHB29mMXw', 'Daria Graph', CURRENT_TIMESTAMP),
('UCJNt3fJISY-DHZhKKqRzSIA', 'Костя Павлов', CURRENT_TIMESTAMP),
('UCisKdSbTsPt16yGuN4iNgrA', 'ZO''R TV', CURRENT_TIMESTAMP),
('UCI-vs_XT8MztGQw8uuYQVSg', 'Oblomoff-stuff', CURRENT_TIMESTAMP),
('UCkQkDhKIiOGrIc3GLbn-SNg', 'DENGIZ TV', CURRENT_TIMESTAMP),
('UCHyou5a9OJPAKCbrCTBXfCA', 'Julia Pushman', CURRENT_TIMESTAMP),
('UC-iacTa9jiuWQYy7bODSNkw', 'Crazy Богдаш', CURRENT_TIMESTAMP),
('UCHCqFvxpDaeXu345_uNZ7qg', 'Miracle', CURRENT_TIMESTAMP),
('UCkGZ4ExmhMEX2S_Jww3EOtA', 'AOneCool', CURRENT_TIMESTAMP),
('UCjzhzbnwYid8BXOYfXfspKw', 'Ric', CURRENT_TIMESTAMP),
('UCh_bylrK2gxzTjNr7eaZPpQ', 'Алиса Лисова', CURRENT_TIMESTAMP),
('UCIOgQIy76jLnEkJH2M2Ggjw', 'ДАНИК', CURRENT_TIMESTAMP),
('UCZkl4La84NS5IdPLeLltRmw', 'Max Rydada', CURRENT_TIMESTAMP),
('UCjAg2-3PgoksLAkYE88S_6g', 'ГРОШІ', CURRENT_TIMESTAMP),
('UCzz2i83tRACGgdWyDuVahRw', 'Domi show', CURRENT_TIMESTAMP),
('UCLlSts9lJLf90vFFNx7le4w', 'Максим Шелков', CURRENT_TIMESTAMP),
('UCmYtYwnf7Z02dQsjhIQclWw', 'Dmitriy Landstop', CURRENT_TIMESTAMP),
('UCkTfsLjGeRPcxu0fFUDEeww', 'Андрей Нифедов', CURRENT_TIMESTAMP),
('UCN5vgyF1h1XwhRqVqV5kb8w', 'Валеришка Games', CURRENT_TIMESTAMP),
('UCNZRrSsvl_NumVIDAVNQOMA', 'PollmixaN', CURRENT_TIMESTAMP),
('UCn1YQ4g_kKwJbt0MUVZfY7A', 'Автосалон Синдиката', CURRENT_TIMESTAMP),
('UCLJl8-mbCfolWMkh1F1qfjA', 'Marina Mogilko', CURRENT_TIMESTAMP),
('UCngph0I4TkZL-vgVQyQbDng', 'shok.uz', CURRENT_TIMESTAMP),
('UCLwwqn62aA71ujOtP4mXzZA', 'Natalie Kisel', CURRENT_TIMESTAMP),
('UClkJx2v_71xq2bPTUaloNEg', 'REDDER', CURRENT_TIMESTAMP),
('UCLvyNJ6P-cjZ1nia7kBFQbA', 'Гуляй, душа!', CURRENT_TIMESTAMP),
('UCNK9Go44l_419LmiyuEUJHg', 'OXANA DOLINKA', CURRENT_TIMESTAMP),
('UCLL5dVnel0uRX3aiyVXQYkw', 'TheGideonGames', CURRENT_TIMESTAMP),
('UCNJwQAU08P3muRZkZUOvx5A', 'Family Play TV', CURRENT_TIMESTAMP),
('UCKQTOGKzcSPuQgflweqce_Q', 'ВУХУУ!', CURRENT_TIMESTAMP),
('UCLaqlgkDM3dkDh4WSbULMEA', 'OneTwo', CURRENT_TIMESTAMP),
('UCkUFua6WbuKcmMDrcxRpH7A', 'Дюшес', CURRENT_TIMESTAMP),
('UCMc5xJoydmPd4M1f31pd6YA', 'FRESH', CURRENT_TIMESTAMP),
('UCLSI-9F_zowzLE_ozfXhjAw', 'Руслан Гладенко', CURRENT_TIMESTAMP),
('UCnQBjLBbZ6TXMwM_D_iaXjQ', 'Юрий Хованский', CURRENT_TIMESTAMP),
('UCo-gAYrvd7WIrCRsNueddtQ', 'ASMR KittyKlaw', CURRENT_TIMESTAMP),
('UCpm6vCgiehSKHtMFFS5ukiA', 'Katy LifeVlog', CURRENT_TIMESTAMP),
('UCQ__rXROBpF6mKjCZ29ij9Q', 'Исцеляющие Медитации', CURRENT_TIMESTAMP),
('UCSoYSTOt1g_Vdo8xCJeQpHw', 'ОХ', CURRENT_TIMESTAMP),
('UCSZ69a-0I1RRdNssyttBFcA', 'Официальный канал КВН', CURRENT_TIMESTAMP),
('UCrz4Io1bYWfW8cJW8cxlhoQ', 'ASATA channel', CURRENT_TIMESTAMP),
('UCOynRdpGiTCNFhCgD0RTe1w', 'SHIMOROSHOW', CURRENT_TIMESTAMP),
('UCPX53dr-NSKoXspKmXanbCw', 'Аид [VyacheslavOO]', CURRENT_TIMESTAMP),
('UCqmx3IZWOUyOSEBttRE0C6w', 'Alexandra Posnova', CURRENT_TIMESTAMP),
('UC_sl0iB9sVbKmc7YJdQA78w', 'Жила-была Царевна', CURRENT_TIMESTAMP),
('UCS-_94qsFjXIn6Rp7AjMnVQ', 'DiLi Play', CURRENT_TIMESTAMP),
('UCuVpbMt4yu4I9eAey3khnGg', 'AdMe', CURRENT_TIMESTAMP),
('UCQVtD_N4OeD-9PshBq7NwyQ', 'ФЕЙГИН LIVE', CURRENT_TIMESTAMP),
('UCpDzpaUTbIkdjkCZ9pmfMrA', 'Coffi Channel', CURRENT_TIMESTAMP),
('UCr0WqmHegJ34WnFObjAHtBg', 'Доктор Демченко', CURRENT_TIMESTAMP),
('UCR8qqzjkpbCdY4yx8axvHYA', 'TheWarpath', CURRENT_TIMESTAMP),
('UCPAa-a3IGoh78Jva5VrbxFw', 'Удивительные Факты', CURRENT_TIMESTAMP),
('UCTh5OcMLA3zquBefXrA45nw', 'Антон ЛАВ Лазарев', CURRENT_TIMESTAMP),
('UCsk9ntn2afzIqInnx2jB8gw', 'Телеканал ПЯТНИЦА', CURRENT_TIMESTAMP),
('UCsSYbcw93UcytV39VTmvQWg', 'Пешка', CURRENT_TIMESTAMP),
('UCdKEBeInDzinQ6MG2HkF7Gw', 'Луномосик', CURRENT_TIMESTAMP),
('UCw25DrmfCz5_yy_Hk1sTQKQ', 'Телеканал Ю', CURRENT_TIMESTAMP),
('UC-jHNWViReG6R_kJ6b45FdQ', 'Family Box', CURRENT_TIMESTAMP),
('UCya1VRd9ps4LkG7bSaEozRA', 'Валеришка Sim', CURRENT_TIMESTAMP),
('UCY-NDR1axEknClGTkCszZow', 'Маша LIL_P', CURRENT_TIMESTAMP),
('UCwrRor4IvrByHGeWoPhddXw', 'Василий Уткин', CURRENT_TIMESTAMP),
('UCZ2-3OqJpwRfIvUGBOKa0_g', 'Raily', CURRENT_TIMESTAMP),
('UCzxsWdAqfZfak63rTC6m1XQ', 'Julia Godunova', CURRENT_TIMESTAMP),
('UCvwfhb4WVf29L7nto41xxVQ', 'Nepeta Страшилки', CURRENT_TIMESTAMP),
('UC7p0GCM88wBsrlv5n5eeCHw', 'ШАСТУН', CURRENT_TIMESTAMP),
('UCXmseTCR4w5q36pupOJKegw', 'Chapitosiki', CURRENT_TIMESTAMP),
('UCuZeiI5pdpgqDojXZujoYgg', 'Поззи', CURRENT_TIMESTAMP),
('UCv7Zff-RjwiRPlvn8g5fMog', 'ПУШЕР', CURRENT_TIMESTAMP),
('UCXkqIJIaTxcbu0jMlcrCJiA', 'Сней', CURRENT_TIMESTAMP),
('UCdmauIL-k-djcct-yMrf82A', 'СТС', CURRENT_TIMESTAMP),
('UCvJSD-tzFTsXThxwN3-X2-g', 'KIRILL SARYCHEV', CURRENT_TIMESTAMP),
('UCVPYbobPRzz0SjinWekjUBw', 'Анатолий Шарий', CURRENT_TIMESTAMP),
('UCYzkb8WCMF0av77kjC6DCXw', 'Покашеварим', CURRENT_TIMESTAMP),
('UCVKnT0vTxDdHKDGTPw2G_lg', 'Holdik Live', CURRENT_TIMESTAMP),
('UCVeIZ3mYEkQzjKVowqgeGTA', 'ШТРЭБУХ', CURRENT_TIMESTAMP),
('UCXEsHh2duNWSsX6K9WbmfIg', 'ПРИЯТНЫЙ ИЛЬДАР', CURRENT_TIMESTAMP),
('UCEK3tT7DcfWGWJpNEDBdWog', 'Киноконцерн "Мосфильм"', CURRENT_TIMESTAMP),
('UCgFFMzzYIYYn3T6M-v8Kfsw', 'Double Bubble', CURRENT_TIMESTAMP),
('UCyJrhZm9KXrzRub3-wD2zWg', 'TheBrianMaps', CURRENT_TIMESTAMP),
('UCvo4dSGxJ3r0ZL6NQJIuG5Q', 'tophype', CURRENT_TIMESTAMP),
('UCTl7rTGi0SROUH_zeXMS_fw', 'Elli Di', CURRENT_TIMESTAMP),
('UC7r_7zmnTa1zi57cbmRKeEQ', 'Cool GAMES', CURRENT_TIMESTAMP),
('UCqZZoXlUEki3H7_GCQrw53A', 'Теремок - Песенки для детей', CURRENT_TIMESTAMP),
('UC4gVKW7oYok8-3vmeIBNB_w', 'Кухня наизнанку', CURRENT_TIMESTAMP),
('UCAFKgdKwF0WZBK9sC1cxlAA', '123 GO! CHALLENGE Russian', CURRENT_TIMESTAMP),
('UC0lT9K8Wfuc1KPqm6YjRf1A', 'AcademeG', CURRENT_TIMESTAMP),
('UC9rUnYrza0heXpO011zNDfQ', 'ОЛЕЖЭ', CURRENT_TIMESTAMP),
('UCUHQKxU-_DWsrwBxlKWgsew', 'ЕГОРИК', CURRENT_TIMESTAMP),
('UCBYvr4SqfGQd5fTmOXVQ4Zw', 'ГЛЕНТ', CURRENT_TIMESTAMP),
('UCAf-RYRpQgxpj8voC29ck7w', 'Hard Play', CURRENT_TIMESTAMP),
('UCWGK2_WVaXWv-QrkgT9-KDw', 'KiKiDo', CURRENT_TIMESTAMP),
('UCnBTGpEQ3LGPW2Shh7fiabg', 'Говорящий Том и Друзья', CURRENT_TIMESTAMP),
('UCrpt82vHWIWZSHtNQxncPrg', 'EdisonPts', CURRENT_TIMESTAMP),
('UCxxeCoakggrZElFkjaKtTng', 'Краймтубер', CURRENT_TIMESTAMP),
('UC2K_8x8aKVEiyPwHRqpyeXg', 'Mikhail Boldurev', CURRENT_TIMESTAMP),
('UCHH3KHUqDJX_CoRbqLy1zNg', 'Александр Пушной', CURRENT_TIMESTAMP),
('UCpJuziZAwEFnoeNGSaxQlCQ', 'Скажи Гордеевой', CURRENT_TIMESTAMP),
('UCL4JRO-eW2JtTxo-XVzxtQg', 'Masha Zoom', CURRENT_TIMESTAMP),
('UCc1lGoEVffJmXTrtd6GCn_A', 'Супер Сус', CURRENT_TIMESTAMP),
('UC8NnhnWIdis9aetrRNqwoeQ', 'ВЕРЬЁМИНА - здоровье и фитнес', CURRENT_TIMESTAMP),
('UCF_LN8QOT93JfSFBRy2swIw', 'Трум Трум Оки Токи', CURRENT_TIMESTAMP),
('UCcGkkZ3cu4wKTJKSNy_fDmw', 'СМОТРИМ. Русские сериалы', CURRENT_TIMESTAMP),
('UCpecK3rLVveAWd6tmvhH_yA', 'Super Tima', CURRENT_TIMESTAMP),
('UCdgF_dQwv4SnbD7X4I3Nl1w', 'Школа векторного массажа и соматики', CURRENT_TIMESTAMP),
('UCr2EXJtFMunvG0CmYE3Tj8A', 'Асафьев Стас', CURRENT_TIMESTAMP),
('UCxf2_-MyDjCVMqIMKDx5MVg', 'Егор Мисливец', CURRENT_TIMESTAMP),
('UCh29SdTOPdjBb-n3Vop1lYg', 'katyakonasova', CURRENT_TIMESTAMP),
('UC-qW30bdL5CoesZG1UFNjbw', 'Amirxon Umarov', CURRENT_TIMESTAMP),
('UCLDEqLXMGf7tATPhB_eF1dA', 'RAMINA', CURRENT_TIMESTAMP),
('UCAyCo_hIuUPaFey8ofdK2Wg', 'BersReview', CURRENT_TIMESTAMP),
('UCdQBRBVsfH0w5F0cZoDlGIQ', 'Юрий Благополучный', CURRENT_TIMESTAMP),
('UCWG86L4tau8SZ4jRqiVco5g', 'Чердак', CURRENT_TIMESTAMP),
('UCTXMeEml1hhGYagq7QZFqcA', 'Садовый Гид', CURRENT_TIMESTAMP),
('UCUC19KkE-mNkI02qrnarynQ', 'Женяша Ларионова', CURRENT_TIMESTAMP),
('UCuOyP59Q8OiqetsjABP8Hhw', 'Илья Соболев', CURRENT_TIMESTAMP),
('UCfV8OBhRRrhCHm-UPX7_1Sg', 'КУБ', CURRENT_TIMESTAMP),
('UCxF6ylvxiQV5m-7Rawr3W7g', 'Макс Брандт', CURRENT_TIMESTAMP),
('UCSM8OMud7Xi6EgG4GcsoNRA', 'Клуб Tube', CURRENT_TIMESTAMP),
('UCd72TnBJrgjj631Ajk2Nf7w', 'Видео от SoLiD''a', CURRENT_TIMESTAMP),
('UCBhga2EHf0JbGyPXkgUiUXg', 'Yumeko', CURRENT_TIMESTAMP),
('UCDaIW2zPRWhzQ9Hj7a0QP1w', 'Руслан Усачев', CURRENT_TIMESTAMP),
('UCO8YHPk43zHgfUFWv9FUttg', 'Сталик Ханкишиев', CURRENT_TIMESTAMP),
('UChZ-HM0EiwFHscypW8Ukp8Q', 'intervyuTV', CURRENT_TIMESTAMP),
('UCP1itCwGbXmHIsNrCIm1Hsw', 'TutorOnline - уроки для школьников', CURRENT_TIMESTAMP),
('UCiWMFQCGvwGSc8QWHOqcQhw', 'Радио Свобода', CURRENT_TIMESTAMP),
('UC-ZROtSKHGERKmfuYL0AryQ', 'ShadowPriestok - Евгений Чернявский', CURRENT_TIMESTAMP),
('UCSJaLHpYLwXyn6eoQz8ATCA', 'Слушай Кайфуй', CURRENT_TIMESTAMP),
('UCSALVSMWF_ck1p8iAt6FqUQ', 'MyNeosha', CURRENT_TIMESTAMP),
('UCTr9AtbJgU0RDsDM1O04_Nw', 'Даша Юрьевна', CURRENT_TIMESTAMP),
('UCSpvoH56m-DxSAfx0X67-mQ', 'Валеришка Play', CURRENT_TIMESTAMP),
('UCPPB1IEliES93yvxHTqxu2w', 'Юлия Смирнова', CURRENT_TIMESTAMP),
('UCsap6IDS_RavvZoqO6_V4oA', 'Restl', CURRENT_TIMESTAMP),
('UCOIRN19VunfPaW7ZfmOKeoQ', '2DROTS', CURRENT_TIMESTAMP),
('UCZNKg6NI7mah4i3dE6m0oYw', 'День ТВ', CURRENT_TIMESTAMP),
('UCn9bv143ECsDMw-kJCNN7QA', 'Чикен Карри', CURRENT_TIMESTAMP),
('UCSLNrD07nnAzfzsIzVYiwkQ', 'Mark King', CURRENT_TIMESTAMP),
('UCVgvnGSFU41kIhEc09aztEg', 'Arzamas', CURRENT_TIMESTAMP),
('UCoAEj6XaIzqxQ5C5OUIGcZA', 'Chuck Review', CURRENT_TIMESTAMP),
('UChsWRtPH1RZ2TCfHF_TP_kA', 'Nellifornication', CURRENT_TIMESTAMP),
('UC6JRrn_7Qe1CZBcQDMieadw', 'ExileShow', CURRENT_TIMESTAMP),
('UCh1lXfVnw2L4w8aBHrTy4zA', 'AuRuM TV', CURRENT_TIMESTAMP),
('UC-hOnt3BktBRpH5UOs3UdLg', 'THRASHER TV', CURRENT_TIMESTAMP),
('UC1iymlgInaX3aOqmh3_wXdA', 'Урожайный огород', CURRENT_TIMESTAMP),
('UCiXFDtLgmHpSbZ8rjk_TJtQ', 'Протоиерей Андрей Ткачёв', CURRENT_TIMESTAMP),
('UCj7bSQWlq2O4lhGxGll5SUA', 'ВПИСКА', CURRENT_TIMESTAMP),
('UCjDwvpIhyfBGz4bbH8bcvUg', 'ДЖАРАХОВ', CURRENT_TIMESTAMP),
('UCW7rz4ElDV55Z2bY2-LbgPw', 'Elena Zavidova', CURRENT_TIMESTAMP),
('UC_8PAD0Qmi6_gpe77S1Atgg', 'Mister Max', CURRENT_TIMESTAMP),
('UCc06CkIbW9nGZhSuUV4I8PQ', 'AdushkinaVlogs', CURRENT_TIMESTAMP),
('UCwK4e2gGMFi8slBSnELJBRg', 'Менеджер Антон', CURRENT_TIMESTAMP),
('UCxh_TkSralaVxmsLNYCXeoQ', 'Odesa Film Studio', CURRENT_TIMESTAMP),
('UCJulUprbsYQg5oDfmAnAtwg', 'navo.tv', CURRENT_TIMESTAMP),
('UCVsZCZaUwfXgbLqvWvcTiiA', 'NTK TV', CURRENT_TIMESTAMP),
('UCWIAgREYZ3j4zc2oQSfUZcw', 'CD LAND VIDEO', CURRENT_TIMESTAMP),
('UCppEZ8eZJ7MaKGdgfAw9wxg', 'aboven', CURRENT_TIMESTAMP),
('UCcartHVtvAUzfajflyeT_Gg', 'Miss Katy', CURRENT_TIMESTAMP),
('UC7HFqjeiRtBPDyZs69_vLGw', 'creative7play', CURRENT_TIMESTAMP),
('UCeeJZoYPrGdyYqI1lRoEN9A', 'Моя анимированная история', CURRENT_TIMESTAMP),
('UCenFYp3Wqneyh2cU3GYTUBw', 'Центральное Телевидение', CURRENT_TIMESTAMP),
('UCjC5MBcnMpT-QDZ8XbrIOIw', 'Настя Туман', CURRENT_TIMESTAMP),
('UCPU28A9z_ka_R5dQfecHJlA', 'RTVI Новости', CURRENT_TIMESTAMP),
('UCraVQW3OiTgfOcsIfS8-lqA', 'RASA MUSIC', CURRENT_TIMESTAMP),
('UCSOSYKMFqMLwko2PfSUTW_A', 'Игорь Лайм', CURRENT_TIMESTAMP),
('UCvph04Sh9CFKAw-gA6y-brQ', 'I_am_puma', CURRENT_TIMESTAMP),
('UChLkH4BtfCeyfk6H7O24Wdw', 'Бубновский', CURRENT_TIMESTAMP),
('UC3p1C503O2eoso8sgKK9KqQ', 'МORIS', CURRENT_TIMESTAMP),
('UC5scTgc8DqV9Xq-xNvgTMPw', 'ПАПА РОБ ШОУ', CURRENT_TIMESTAMP),
('UC8zQiuT0m1TELequJ5sp5zw', 'BBC News - Русская служба', CURRENT_TIMESTAMP),
('UCA2MqdDNpHHStN3_QDIzloQ', 'Марти', CURRENT_TIMESTAMP),
('UCdOUvNFp8y6KTkswzeu7naQ', 'Игорь Рыбаков', CURRENT_TIMESTAMP),
('UCEbpRAmSB6ZWMjyNTvpIkFA', 'ЛАРИН', CURRENT_TIMESTAMP),
('UCiln3t3qx2yA44IHPqdGnrw', 'Tilka Play', CURRENT_TIMESTAMP),
('UCKCVeAihEfJr-pGH7B73Wyg', 'УНІАН', CURRENT_TIMESTAMP),
('UCmXGqfEsluA1fID55bVexjw', 'Tanya StreLove', CURRENT_TIMESTAMP),
('UCOyKtXwAm6ALJ1-r3nugR5Q', 'CheZee', CURRENT_TIMESTAMP),
('UCtNX4bdqJqsaCyJMJvzq-Fw', 'Brawl Stars MMA', CURRENT_TIMESTAMP),
('UCT-uAtuGWsDuMZoxVobmWkg', 'UZBEK TV', CURRENT_TIMESTAMP),
('UCv9n8Z9zQ8luNEOnro9D_Cg', 'Ozodlik Radiosi', CURRENT_TIMESTAMP),
('UCZIFo5MmrUJS5JbLOxgnHuQ', 'Дмитрий Гордон', CURRENT_TIMESTAMP),
('UC3Jdf5TkvbU7Kk0roMCoX1Q', 'Kinder Surprise Eggs Rustama', CURRENT_TIMESTAMP),
('UCktiC07wsJGQQJGv9WnYVXA', 'Азбука Рисования', CURRENT_TIMESTAMP),
('UC2hsvTzqdjsGOUnM-Ilai6Q', 'Combat Crew', CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
